### ISSUE TITLE
Bootstrapping of circular dependencies

### ISSUE THREAD

**Issue by voxik** [fedora-eln/eln#1]
Just recently, I have noticed [this](http://koji.fedoraproject.org/koji/buildinfo?buildID=1599965) failed build of rubygem-railties. It was immediately clear to me, that the build failed, because it has circular dependencies with other packages. So I just wanted to rise this topic.

The packages are using [bootstrap flag](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bootstrapping). The question is how to make ELN to benefit from them.

Also please note that these packages were build in side tag. That is probably also something to consider.

**Comment by hroncok** [comment]
BTW Side tag builds were discussed at lengths when ELN was proposed.

**Comment by sgallagher** [comment]
This should now be resolved by the new build-syncing mechanism.
