### ISSUE TITLE
TASK: enable ima signing

### ISSUE THREAD

**Issue by nirik** [fedora-eln/eln#100]
### What does the ELN SIG need to do?
*
Decide if you would like ima signing enabled for eln packages. 

Currently it's not enabled. autosign just signs packages with the fedora-37 rpm gpg key. 
Currently Fedora rawhide _is_ using ima signatures (with a fedora-37-ima key). 

If eln would like this enabled, we can do so. If not, just close this and we don't have to enable it.

**Comment by sgallagher** [comment]
We will discuss this at the meeting on 2022-07-29

**Comment by sgallagher** [comment]
The ELN SIG agreed to enable IMA signing. @nirik has volunteered to take the appropriate actions.

**Comment by nirik** [comment]
This is done/enabled.
