### ISSUE TITLE
TASK: Review Rawhide packages in Content Resolver

### ISSUE THREAD

**Issue by asamalik** [fedora-eln/eln#103]
Looking at the [ELN Package Set in Content Resolver](https://tiny.distro.builders/view-packages--view-eln.html), it shows that some packages are pulled in from Rawhide. This is expected in some cases, but not in all.

For example, search for `tuned-profiles-sap-hana` and you'll see that on `aarch64` and `s390x` it's coming from Rawhide, and on `ppc64le` and `x86_64` it's coming from the `SAPHANA` repo which is part of ELN. Knowing the `SAPHANA` repo only exists for `ppc64le` and `x86_64` and looking at the package name, it feels this package was only supposed to be added to these two arches.

This can be easily fixed: click on [the package](https://tiny.distro.builders/view-rpm--view-eln--tuned-profiles-sap-hana.html), then on [its workload](https://tiny.distro.builders/config-workload--sst_cs_infra_services-performance-tuning.html), click [edit configuration](https://github.com/minimization/content-resolver-input/blob/main/configs/sst_cs_infra_services-performance-tuning.yaml), and change the config to something like:

```
...
arch_packages:
  x86_64:
    - tuned-profiles-sap-hana
  ppc64le:
    - tuned-profiles-sap-hana
...
```
(... and remove it from the `packages` list.)

Should we review the packages coming from Rawhide, and see if they should be there in the first place? And either fix it ourselves, or at least notify the maintainers?

**Comment by yselkowitz** [comment]
At this point, rawhide packages only end up being used for new build dependencies (which should then be rebuilt by CR) or when ELN dependencies are broken.  Right now, there are only two packages being pulled in from rawhide, and fixes are in flight.  This is something that we need to monitor on an ongoing basis but isn't a big problem anymore, so closing.
