### ISSUE TITLE
TASK: Review 'placeholder' packages in Content Resolver

### ISSUE THREAD

**Issue by asamalik** [fedora-eln/eln#104]
There's a few package placeholders in the [ELN Package Set in Content Resolver](https://tiny.distro.builders/view-packages--view-eln.html) (search for 'placeholder'). But some of them definitely exist in Fedora ELN. Let's review this and update the workloads.

**Comment by yselkowitz** [comment]
A few were converted to real packages last year.  AFAICS all remaining placeholders are either not in Fedora or are leaves not wanted in ELN (e.g. fence-agents due to its many dependencies, which are bundled in RHEL).
