### ISSUE TITLE
fedora-eln builds failing for not having the epel-rpm-macros common for the RHEL

### ISSUE THREAD

**Issue by xsuchy** [fedora-eln/eln#107]
Copied from https://github.com/fedora-copr/copr/issues/2427

Hello,
some of my packages fail because they are missing epel-rpm-macros in the build repository.
As ELN builds otherwise mimic the RHEL, please would it be possible to add epel-rpm-macros there?

For example:
https://download.copr.fedorainfracloud.org/results/rebus/infosec/fedora-eln-x86_64/05096388-radare2/root.log.gz

Thank you
Michal Ambroz

**Comment by hroncok** [comment]
RHEL does not have epel-rpm-macros and the example link has expired.

**Comment by sgallagher** [comment]
I replied on the original ticket. There's nothing for us to do here.
