### ISSUE TITLE
TASK: Old builds in ELN

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#108]
### What does the ELN SIG need to do?

I've noticed recently that I get errors like this in ELN:

```
DEBUG util.py:443:  No matching package to install: 'python3dist(hatchling) >= 1.12.2'
```

```
  - nothing provides (python3.11dist(tox) < 4~~ with python3.11dist(tox) >= 3.15) needed by python3-tox-current-env-0.0.8-3.eln120.noarch
```

Apparently, there are some old versions of packages in ELN:

```
$ repoquery -q --repo=koji python3-tox-current-env
python3-tox-current-env-0:0.0.11-1.fc38.noarch

$ repoquery -q --repo=kojieln python3-tox-current-env
python3-tox-current-env-0:0.0.8-3.eln120.noarch

$ repoquery -q --repo=koji python3-hatchling
python3-hatchling-0:1.12.2-1.fc38.noarch

$ repoquery -q --repo=kojieln python3-hatchling
python3-hatchling-0:1.11.1-1.eln122.noarch
```

Is something stuck? Should the more recent rawhide builds be tagged in instead?

**Comment by hroncok** [comment]
I've built [python-tox-current-env-0.0.11-1.eln125](https://bodhi.fedoraproject.org/updates/FEDORA-2023-63eae4cac8) manually for now.

**Comment by hroncok** [comment]
Another one:

```
$ repoquery -q --repo=koji python3-rich
python3-rich-0:13.0.0-1.fc38.noarch

$ repoquery -q --repo=kojieln python3-rich
python3-rich-0:12.6.0-2.eln122.noarch
```

**Comment by sgallagher** [comment]
It looks like none of those packages appear in the [Content Resolver](https://tiny.distro.builders/view-sources--view-eln.html), so they aren't auto-rebuilt. At some point in the past (recent or not), they were built for ELN.

We have automation that is supposed to untag all packages that are no longer part of the content set once a day, but that appears not to be working exactly as intended. I will dig into it.

**Comment by hroncok** [comment]
The fact that python-tox-current-env does not appear in the ELN [Content Resolver](https://tiny.distro.builders/view-sources--view-eln.html) worries me a bit considering e.g. this buildrequires it: https://tiny.distro.builders/view-srpm--view-eln--pyproject-rpm-macros.html

**Comment by hroncok** [comment]
```
$ repoquery -q --repo=eln-{baseos,appstream,crb}{,-source} --whatrequires python3-tox-current-env
(nothing)
$ repoquery -q --repo=eln-{baseos,appstream,crb}{,-source} --whatrequires 'python3dist(tox-current-env)'
marshalparser-0:0.3.3-2.eln123.src
micropipenv-0:1.4.5-1.fc38.src
pyparsing-0:3.0.9-2.eln120.src
pyproject-rpm-macros-0:1.5.0-1.eln124.src
python-distro-0:1.8.0-1.eln122.src
python-iniconfig-0:1.1.1-10.eln124.src
python-iniparse-0:0.5-3.eln120.src
python-setuptools_scm-0:7.1.0-1.eln124.src
python-toml-0:0.10.2-10.eln123.src
python-tomli-w-0:1.0.0-4.eln120.src
python-tornado-0:6.2.0-2.eln120.src

$ repoquery -q --repo=eln-{baseos,appstream,crb}{,-source} --whatrequires python3-hatchling
(nothing)
$ repoquery -q --repo=eln-{baseos,appstream,crb}{,-source} --whatrequires 'python3dist(hatchling)'
python-jsonschema-0:4.17.3-1.eln124.src


```

**Comment by hroncok** [comment]
Another example is https://tiny.distro.builders/view-rpm--view-eln--python3-toml.html (error 404) which is:

```
$ repoquery -q --repo=eln-{baseos,appstream,crb}{,-source} --whatrequires 'python3.11dist(toml)'
sip6-0:6.6.2-2.eln120.x86_64
```

And https://tiny.distro.builders/view-srpm--view-eln--sip6.html is also error 404 despite being in ELN repositories.


I even celebrated the removal of python3-toml from ELN in the team last week and closed https://bugzilla.redhat.com/show_bug.cgi?id=2135349

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--python3-tox-current-env.html and https://tiny.distro.builders/view-rpm--view-eln--python3-hatchling.html are back

Unfortunately, so is https://tiny.distro.builders/view-rpm--view-eln--python3-tomli.html and https://tiny.distro.builders/view-rpm--view-eln--python3-toml.html back in ELN.

**Comment by sgallagher** [comment]
The current results are not trustworthy, because of an issue with the compose. I've fixed the problem and the Content Resolver should be accurate by about 00:00 UTC.

**Comment by sgallagher** [comment]
I think this is resolved now, but I wouldn't mind a re-review here.

**Comment by hroncok** [comment]
At least for the packages reported:

```
$ repoquery -q --repo=koji python3-tox-current-env
python3-tox-current-env-0:0.0.11-2.fc38.noarch
$ repoquery -q --repo=kojieln python3-tox-current-env
python3-tox-current-env-0:0.0.11-2.eln125.noarch
$ repoquery -q --repo=koji python3-hatchling
python3-hatchling-0:1.12.2-2.fc38.noarch
$ repoquery -q --repo=kojieln python3-hatchling
python3-hatchling-0:1.12.2-2.eln125.noarch
$ repoquery -q --repo=koji python3-rich
python3-rich-0:13.0.0-2.fc38.noarch
$ repoquery -q --repo=kojieln python3-rich
python3-rich-0:13.0.0-2.fc38.noarch
```
