### ISSUE TITLE
TASK: Add `fwupd-efi` package

### ISSUE THREAD

**Issue by pablomh** [fedora-eln/eln#109]
### What does the ELN SIG need to do?
Add `fwupd-efi` to the list of installed packages in the content resolver in ELN only.

Without that package, it's not possible to run `fwupdmgr update` on an EFI system.

The package is not a dependency of `fwupd` as explained in [Bug 1993508 - /usr/libexec/fwupd/efi/fwupdx64.efi cannot be found](https://bugzilla.redhat.com/show_bug.cgi?id=1993508) so it'd be convenient to add it to the content resolver to the same places where `fwupd` is mentioned.

**Comment by sgallagher** [comment]
Please send a merge request for https://github.com/minimization/content-resolver-input/blob/main/configs/sst_desktop_firmware_bootloaders-fwupd.yaml to include this package.

**Comment by pablomh** [comment]
Not being a part of the SST I wanted to request here first and wait for instructions :) Will do right away.

**Comment by pablomh** [comment]
Thanks @sgallagher! Requested in https://github.com/minimization/content-resolver-input/pull/759.
