### ISSUE TITLE
TASK: Add `iwlax2xx-firmware` package

### ISSUE THREAD

**Issue by pablomh** [fedora-eln/eln#110]
### What does the ELN SIG need to do?
Add `iwlax2xx-firmware` to the list of installed packages in the content resolver.

Without this package some recent laptops (like the Lenovo Thinkpad P1 Gen 3) will boot without network after a fresh ELN installation.

**Comment by sgallagher** [comment]
Please send a merge request for https://github.com/minimization/content-resolver-input/blob/main/configs/sst_kernel_maintainers-kernel-base.yaml

**Comment by pablomh** [comment]
Thanks @sgallagher!

Requested in https://github.com/minimization/content-resolver-input/pull/758.
