### ISSUE TITLE
TASK: /usr/bin/ruby conflicts between attempted installs of ruby-3.2.0-177.eln124.x86_64 and rubypick-1.1.1-17.eln120.noarch

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#111]
### What does the ELN SIG need to do?
 * Figure out how to properly solve the following problem:

Apparently, this happens in ELN and prevents some packages from building (e.g. pre-commit):

```
$ mock -r fedora-eln-x86_64 --enablerepo=local install rubypick ruby
...
Error: Transaction test error:
  file /usr/bin/ruby conflicts between attempted installs of ruby-3.2.0-177.eln124.x86_64 and rubypick-1.1.1-17.eln120.noarch
```

This does not happen in Rawhide:

```
$ mock -r fedora-rawhide-x86_64 --enablerepo=local install rubypick ruby
...
Installed:
  ruby-3.2.0-177.fc38.x86_64  ruby-libs-3.2.0-177.fc38.x86_64  rubypick-1.1.1-17.fc37.noarch 
```

I believe this is caused by this construct from the ruby specfile:

```
%if 0%{?fedora} >= 19
%bcond_without rubypick
%endif

...
# Rename the ruby executable. It is replaced by RubyPick.
%{?with_rubypick:mv %{buildroot}%{_bindir}/%{name}{,-mri}}

...

%files
...
%{_bindir}/%{name}%{?with_rubypick:-mri}
```

This means the rubypick integration is disabled in ELN but as long as rubypick is actually used in ELN, that si kinda problematic.

rubypick is marked as unwanted in [Unwanted packages for Ruby](https://tiny.distro.builders/config-unwanted--sst_cs_apps-unwanted-ruby.html) as well as in [Unwanted ELN packages](https://tiny.distro.builders/config-unwanted--unwanted-eln-packages.html), so the spec conditional is doing the right thing. However, this presents an interesting challenge for ELN: How to write conditionals based on the actual presence of a package in ELN?

**Comment by hroncok** [comment]
BTW ruby also has `Suggests: rubypick` even when built `--without rubypick`, that seems like an oversight (but is not causing this problem).

**Comment by tdawson** [comment]
Yep.  I'll ask vit about this.  Since he works both sides (fedora and rhel) he should know what we really want it to be.

**Comment by tdawson** [comment]
Looks like I already talked with Vit about this.  rubypick should not be in RHEL.  If any package is pulling it in, we need to fix it.  Looking at what is pulling it in.

**Comment by tdawson** [comment]
The package is pre-commit 
I have created a pull request to change rubypick to ruby.
https://src.fedoraproject.org/rpms/pre-commit/pull-request/11

**Comment by hroncok** [comment]
FWIW pre-commit also has no business in RHEL and rubypick is also pulled in by [ruby-default-gems](https://tiny.distro.builders/view-rpm--view-eln--ruby-default-gems.html)

**Comment by tdawson** [comment]
pre-commit is a build requirement of three unwanted python packages.  So I do agree that is shouldn't be in there.  But from what I could see, the only reason rubypick is in pre-commit is someone had to choose between ruby and rubypick, and they chose rubypick.
Although ruby-default-gems might work with rubypick, it doesn't specifically choose it.  It will run with either.  From what I can see, pre-commit is the only package currently in ELN that specifically requires rubypick.

**Comment by hroncok** [comment]
Thanks. I don't know if the Suggest thing mentioned earlier won't pull in rubypick instead of ruby somewhere, but I guess we'll see.

**Comment by hroncok** [comment]
I wanted to build pre-commit in ELN but now I got:

```
Error: 
 Problem 1: package python3-dnf-4.14.0-2.fc38.noarch requires libmodulemd >= 2.9.3, but none of the providers can be installed
  - package libmodulemd-2.14.0-5.eln125.i686 requires libglib-2.0.so.0, but none of the providers can be installed
  - package libmodulemd-2.14.0-5.eln125.i686 requires libgobject-2.0.so.0, but none of the providers can be installed
  - package dnf-4.14.0-2.fc38.noarch requires python3-dnf = 4.14.0-2.fc38, but none of the providers can be installed
  - package glib2-2.74.1-3.fc38.i686 requires libgnutls.so.30, but none of the providers can be installed
  - conflicting requests
  - nothing provides libunistring.so.2 needed by gnutls-3.7.8-11.eln125.i686
 Problem 2: package python3-dnf-plugins-core-4.3.1-2.eln125.noarch requires python3-dbus, but none of the providers can be installed
  - package python3-dbus-1.3.2-2.eln125.i686 requires libglib-2.0.so.0, but none of the providers can be installed
  - package dnf-plugins-core-4.3.1-2.eln125.noarch requires python3-dnf-plugins-core = 4.3.1-2.eln125, but none of the providers can be installed
  - package glib2-2.74.1-3.fc38.i686 requires libgnutls.so.30, but none of the providers can be installed
  - conflicting requests
  - nothing provides libunistring.so.2 needed by gnutls-3.7.8-11.eln125.i686
(try to add '--skip-broken' to skip uninstallable packages)
```

:sob:

**Comment by hroncok** [comment]
See https://pagure.io/releng/issue/11175#comment-836991

**Comment by hroncok** [comment]
pre-commit without the rubypick dependency built in ELN

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--rubypick.html errors 404. That's nice.

```
$ mock -r fedora-eln-x86_64 --enablerepo=local install rubypick ruby
...
Error: Transaction test error:
  file /usr/bin/ruby conflicts between attempted installs of ruby-3.2.0-177.eln124.x86_64 and rubypick-1.1.1-18.fc38.noarch
```

That is still the same error but this time it conflicts with a Rawhide build so it's expected I guess.


As a follow-up, I've sent https://src.fedoraproject.org/rpms/ruby/pull-request/149 anyway.

Thank you @tdawson.
