### ISSUE TITLE
TASK: new Waiting status on ELN Rebuild Status page

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#113]
### What does the ELN SIG need to do?
* There is always some degree of lag time between when a rawhide build and the counterpart ELN build.  Currently, during that window, the rawhide build is tagged into ELN, and the package is shown as FAILED.  This means that someone triaging ELN build failures has to first go to the failed build, possibly see a successful (previous) build, then browse from their to the overall package status to realize what's actually going on, all of which consumes time and energy.
* Instead, the status page should include a new status, e.g. Waiting, for packages which now have a rawhide build but automation has not yet attempted an ELN build.  In other words, packages would progress from Waiting to Building to either SUCCESS or FAILED.  That would leave FAILED for cases where the ELN build has been attempted but was unsuccessful, and therefore intervention is certainly needed.

**Comment by sgallagher** [comment]
Yeah, this would be a good enhancement. I'll see if I can figure out a way to do this without a major re-architecting of the code.

**Comment by yselkowitz** [comment]
@sgallagher you mentioned this wouldn't be possible without rearchitecting DBS?

**Comment by sgallagher** [comment]
The short version is this: DBS is basically stateless. We listen for tagging events and trigger builds. The rebuild status page is done by querying Koji for historical data.

Keeping track of the tasks (and in a way that would be persistent and tolerant of crashes) is a significant change that probably requires making DBS stateful from end-to-end.

My personal feeling is that it's not currently cost-effective to do this, though there are a few other things that might be simplified or made more robust by such a stateful architecture. Right now, I'd say this isn't worth doing unless we end up rewriting DBS for other reasons.
