### ISSUE TITLE
TASK: remove python-hypothesis from ELN buildroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#115]
### What does the ELN SIG need to do?
* python-hypothesis has been listed as unwanted in RHEL/ELN, but is used as a test dependency of a number of packages.  (It also itself pulls in a bunch of unwanted build dependencies, although that could be fixed by changing the `el9` conditional therein to just `rhel`.)

According to [Content Resolver](https://tiny.distro.builders/view-rpm--view-eln--python3-hypothesis.html), the remaining consumers are:

- [x] pytest
- [x] python-attrs: https://src.fedoraproject.org/rpms/python-attrs/pull-request/14
- [x] python-CommonMark: drop via https://src.fedoraproject.org/rpms/clang/pull-request/205, https://src.fedoraproject.org/rpms/llvm/pull-request/171, and https://src.fedoraproject.org/rpms/bpftrace/pull-request/5
- [x] python-dateutil: https://src.fedoraproject.org/rpms/python-dateutil/pull-request/11
- [x] python-iso8601: https://src.fedoraproject.org/rpms/python-iso8601/pull-request/8
- [x] python-jmespath: https://src.fedoraproject.org/rpms/python-jmespath/pull-request/8
- [x] python-mccabe: drop via https://src.fedoraproject.org/rpms/cloud-init/pull-request/35
- [x] python-packaging: https://src.fedoraproject.org/rpms/python-packaging/pull-request/25
- [x] python-pynacl: drop via https://src.fedoraproject.org/rpms/python-PyMySQL/pull-request/8
- [x] python-pyrsistent: https://src.fedoraproject.org/rpms/python-pyrsistent/pull-request/6
- [x] python-pytest-asyncio: https://src.fedoraproject.org/rpms/python-pytest-asyncio/pull-request/5
- [x] python-wcag-contrast-ratio: dropped
- [x] subunit: drop via https://github.com/fedora-eln/eln/issues/125

/cc @hroncok

**Comment by hroncok** [comment]
Hey. I'll take care of finishing our packages which unfortunately are all but python-jmespath, python-pyrsistent, python-iso8601.

**Comment by yselkowitz** [comment]
So we'll still need to file PRs for those three?

**Comment by hroncok** [comment]
> So we'll still need to file PRs for those three?

To clarify: I suggested on Matrix/IRC that instead of tedious ping-pong interactions about pull requests that are good enough for @yselkowitz but not good enough for me, it might be easier for both of us if you folks tell me what needs to be done and I do it my way. When I said that I meant **packages I co-maintain in Fedora or packages Python-Maint maintains in RHEL**. Unfortunately, I did not mean this as a general offer to help send PRs to other packages (and have possibly tedious ping-pong interactions with their maintainers), sorry for not making that clear.

So yes, you either need to file PRs for those three (one is already open) or find their RHEL maintainers and ask them to do it.

**Comment by hroncok** [comment]
- python-attrs waiting for the primary maintainer's feedback
 - python-dateutil https://bodhi.fedoraproject.org/updates/FEDORA-2023-2629306382
 - python-packaging https://bodhi.fedoraproject.org/updates/FEDORA-2023-e14f1f6eed

**Comment by yselkowitz** [comment]
PRs posted for the rest.

**Comment by hroncok** [comment]
- python-attrs https://bodhi.fedoraproject.org/updates/FEDORA-2023-bdd674c0e4

**Comment by yselkowitz** [comment]
@hroncok added another batch of reverse dependencies.  If any of those are unwanted or only dependencies of unwanted packages, please let us know.

**Comment by hroncok** [comment]
[python-mccabe](https://tiny.distro.builders/view-rpm--view-eln--python3-mccabe.html) is only a dependency of unwanted python-flake8.

**Comment by hroncok** [comment]
python-wcag-contrast-ratio is ours and I will handle it.

**Comment by hroncok** [comment]
python-pytest-asyncio is pulled in by unwanted ipython/jupyter stack but also others. It already only runs the tests `%if %{undefined el9}` and that could be replaced with `%if %{undefined rhel}` .

**Comment by hroncok** [comment]
python-pytest-asyncio https://bodhi.fedoraproject.org/updates/FEDORA-2023-1d498bb149

**Comment by hroncok** [comment]
> python-wcag-contrast-ratio is ours and I will handle it.

https://src.fedoraproject.org/rpms/python-pygments/pull-request/23

**Comment by hroncok** [comment]
> > python-wcag-contrast-ratio is ours and I will handle it.
> 
> https://src.fedoraproject.org/rpms/python-pygments/pull-request/23

https://bodhi.fedoraproject.org/updates/FEDORA-2023-c48ddaa1ba

**Comment by yselkowitz** [comment]
This package has been completely removed from the ELN buildroot.
