### ISSUE TITLE
TASK: add BuildRequires: pyproject-rpm-macros where needed

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#116]
### What does the ELN SIG need to do?
* Recent changes to pyproject-rpm-macros result in a need to explicitly BuildRequires it to use its macros for RHEL/ELN builds unless `%pyproject_buildrequires` is used, which inserts it automatically.  (On Fedora, python3-devel pulls it in, but not in RHEL so that it lands in CRB.)  As a result, any pyproject-based Python packages that do not use `%pyproject_buildrequires` will fail to build in ELN, RHEL 10, or even EPEL 10 without the BuildRequires.
* Therefore, any related ELN FTBFS since the F38 mass rebuild should be fixed in this way, regardless if the package is wanted in RHEL 10 or not.  It might take a while to get it out of the deptree, so fixing it now keeps the FAILED queue clearer, and it will still be beneficial if/when built for EPEL 10.  A revbump in rawhide is not needed for this fix, as these ELN builds currently fail.
* The packages currently affected:

- [x] python-bash-kernel
- [x] python-jupyter-sphinx
- [x] python-latexcodec
- [x] python-pybtex
- [x] python-pybtex-docutils
- [x] python-pydata-sphinx-theme
- [x] python-pyproject-metadata
- [x] python-pytest-datadir
- [x] python-pytest-regressions
- [x] python-repoze-sphinx-autointerface
- [x] python-sphinx-autobuild
- [x] python-sphinx-design
- [x] python-sphinx-sitemap
- [x] python-sphinx-theme-builder
- [x] python-sphinx_rtd_theme
- [x] python-sphinxcontrib-bibtex
- [x] python-sphinxext-rediraffe
- [x] subunit

/cc @hroncok

**Comment by hroncok** [comment]
python-repoze-sphinx-autointerface and python-sphinx_rtd_theme are maintained by members of the Red Hat Python Maint team and unless there is a technical reason not to use `%pyproject_buildrequires`, I'll add it.

All of the rest is maintained by jjames (FAS) who does not like generated buildrequires. I'll ask them about a mass change. to add the missing BRs.

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python-repoze-sphinx-autointerface/pull-request/2
https://src.fedoraproject.org/rpms/python-sphinx_rtd_theme/pull-request/11

Looks like both packages were inherited from jjames as well.

**Comment by hroncok** [comment]
All done.

**Comment by yselkowitz** [comment]
Thanks.  Leaving this open until the rest of the Python build failures are accounted for, but they should be unrelated.

**Comment by yselkowitz** [comment]
Looks like we're set now.
