### ISSUE TITLE
TASK: Skip auto-tagging of openssl

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#119]
### What does the ELN SIG need to do?
* As became apparent from the recent buildroot breakage, Fedora and RHEL/ELN openssl are not fully compatible.  Therefore, as has been done with other such cases (most recently, gtk3/gtk4), to help avoid future breakage, openssl should skip auto-tagging, but should continue to be auto-built.

**Comment by sgallagher** [comment]
I looked into things, and I was incorrect in my statement earlier. The API/ABI is no different, just the available algorithms. So there is no ABI-compatibility issue to avoid.
