### ISSUE TITLE
Compose needs to include fedora-release-eln in BaseOS

### ISSUE THREAD

**Issue by sctweedie** [fedora-eln/eln#12]
For modules, dnf requires that there is a platform:eln dependency available in the default repos.

Our current composes include fedora-release-eln.noarch in the images (the fedoraci container image includes it) and in the Everything repo; but it is not in BaseOS itself.  And as the Everything repo is not enabled by default, we fail to find the platform dependency and module enablement fails.

The solution is to include fedora-release-eln in the BaseOS repo.

The workaround is to manually enable the Everything repo locally.

**Comment by hroncok** [comment]
> Our current composes include fedora-release-eln.noarch in the images and in the Everything repo; but it is not in BaseOS itself.

This also breaks mock, see https://github.com/rpm-software-management/mock/pull/649#issuecomment-717548383

**Comment by sgallagher** [comment]
I think this is fallout from the change to using comps.xml instead of the Content Resolver for defining the BaseOS/AppStream split. I'll look into it.

**Comment by sctweedie** [comment]
@hroncok This should be fixed by https://src.fedoraproject.org/rpms/fedora-release/pull-request/157 and modular dependencies work for me once more in current composes.

Can you check if mock is fixed?  We can close this if there are no other concerns.

**Comment by hroncok** [comment]
Thanks. The problem with missing fedora-release-eln is fixed, but mock is still broken due to missing glibc-minimal-langpack, see https://github.com/rpm-software-management/mock/pull/649#issuecomment-718248749

**Comment by sctweedie** [comment]
OK, let's close this issue and we can open another one as needed.  Thanks!
