### ISSUE TITLE
TASK: Remove %{?eln} conditional from python-cryptography

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#120]
### What does the ELN SIG need to do?
* In https://src.fedoraproject.org/rpms/python-cryptography/pull-request/18 an `%{?eln}` conditional was added by @tiran
* I argued against that
  * > Using the `%{?eln}` conditional requires approval by the ELN SIG. Wouldn't it be better to use `%{?rhel}` instead to also make this work in RHEL?
* @yselkowitz and @sgallagher agreed with me
  * > I agree, `%{?eln}` is definitely the wrong choice here
* @sgallagher merged the PR anyway 
  * > For the sake of getting this working in ELN, I'm going to go ahead and merge this and build it.  We can resolve the remaining questions after the new year.
* This package will likely fail to build in RHEL 10
* "The remaining questions" were not resolved in ~3 months, I've tried to bump this in https://src.fedoraproject.org/rpms/python-cryptography/pull-request/18 but communication in closed Fedora PRs tends to get lost, hence opening this ticket here. Please remove `%{?eln}` conditional from python-cryptography. Thanks.

**Comment by hroncok** [comment]
For the record, the package now fails to build in ELN for unrelated reasons anyway, a fix is included as an extra commit in https://src.fedoraproject.org/rpms/python-cryptography/pull-request/22

**Comment by yselkowitz** [comment]
@hroncok since you already have a PR up, do you want to just make that unconditional there?

**Comment by hroncok** [comment]
I can do that if that's the consensus.

**Comment by yselkowitz** [comment]
That's how I read @sgallagher's comment (who will surely correct me if he disagrees or changed his mind), and this variable has already been added unconditionally to other packages.

**Comment by sgallagher** [comment]
Yes, I agree. Let's make it unconditional.

**Comment by hroncok** [comment]
Pushed the commit to https://src.fedoraproject.org/rpms/python-cryptography/pull-request/22

**Comment by yselkowitz** [comment]
Thanks for keeping track of this @hroncok

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python-cryptography/c/55eaa10d2d97f19c966ba4c3e039f420b4f779bc?branch=rawhide

**Comment by tiran** [comment]
`OPENSSL_ENABLE_SHA1_SIGNATURES=yes` should not be defined on Fedora. It's only necessary on RHEL/ELN, because OpenSSL is modified to block SHA-1 signature creation and validation.

Latest version of python-cryptography has a better way to deal with lack of SHA-1 support. I have created PR https://src.fedoraproject.org/rpms/python-cryptography/pull-request/23 to drop `OPENSSL_ENABLE_SHA1_SIGNATURES` and to mark SHA-1 signatures as unsupported on RHEL/ELN.

**Comment by hroncok** [comment]
Thanks. Let's continue the discussion of the best solution there. The only reason this ticket was needed was that the first PR was merged with "we'll figure out stuff later".
