### ISSUE TITLE
TASK: temporarily restore autotag/autobuild of texlive, texlive-base

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#121]
### What does the ELN SIG need to do?
* autotag/autobuild of texlive and texlive-base was halted in preparation for RHEL-like builds of each to be maintained in their `eln` branches.
* However, these have yet to be created (the dist-git branches are empty), resulting in ELN falling behind rawhide.  Unfortunately, due to a version bump in biber (which *did* land in ELN) that required a simultaneous update to these (which didn't happen as explained above), the ELN buildroot is now broken wrt texlive, and any packages which BuildRequire that subsystem are currently FTBFS.
* I have kicked off builds of these packages based on rawhide as a short-term workaround, and once complete will attempt to retry builds which failed for this reason.
* To avoid a repeat of this scenario, autotag/autobuild of texlive and texlive-base should be resumed until such time that RHEL-like ELN builds are actually ready to go.

**Comment by sgallagher** [comment]
https://gitlab.com/redhat/centos-stream/ci-cd/distrosync/distrobuildsync-config/-/commit/bd6dc91c06b31bd5d111bbe31e082c1e966a43e8
