### ISSUE TITLE
TASK: Tag in marshalparser-0.3.4-2.eln126 and prevent the situation in the future

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#122]
### What does the ELN SIG need to do?

See https://bodhi.fedoraproject.org/updates/?packages=marshalparser

I've built marshalparser-0.3.4-2.eln126  and marshalparser-0.3.4-2.fc39 simultaneously (I don't normally trigger ELN builds manually, but this change was intended for ELN, so I did) and the ELN build finished sooner.

Hence marshalparser-0.3.4-2.fc39 was tagged into eln after marshalparser-0.3.4-2.eln126. I suppose an automatic ELN rebuild did not happen or failed (the NVR already exists in Koji). Ever since, ELN contains marshalparser-0.3.4-2.fc39 instead of marshalparser-0.3.4-2.eln126.

 * Please tag in marshalparser-0.3.4-2.eln126.
 * Please adjust the tooling so when this happens, the Rawhide build is not tagged in at all (or the ELN build is tagged in instead of the skipped/failed rebuild). 

Thanks

**Comment by hroncok** [comment]
A similar situation may repeat when an ELN-specific change is built in ELN only and the package is later built in Rawhide (perhaps accidentally) from the same commit at any time, even weeks later.

**Comment by sgallagher** [comment]
I've manually tagged in marshalparser-0.3.4-2.eln126 just now.

Solving this generally could be tricky as we don't actually know for certain what NVR the rebuild will have (since the ELN build number may have changed since the last attempt). We don't currently watch for the build to complete/fail, so we don't have a simple place to trigger on this. I'll give it some thought.

**Comment by hroncok** [comment]
My thoughts assuming there is a program that currently handles this:

 1. A build lands in Rawhide
 2. The Rawhide build is tagged to ELN
 3. An ELN rebuild is triggered

What if it does:

 1. A build lands in Rawhide
 2. A check is performed to see if the currently tagged ELN build was made from the same commit and/or has a "similar enough" version-release. If so, end here.
 3. The Rawhide build is tagged to ELN
 4. An ELN rebuild is triggered

**Comment by hroncok** [comment]
Koji should be able to tell the commit. A newer commit would have the old commit in the ancestors (unless the ELN build was made from a non-rawhide branch, which would be... unusual).

**Comment by sgallagher** [comment]
We do have some packages that are built from the `eln` branch (such as `crypto-policies`), so there would be an issue if we re-added the package to the auto-rebuild, but that could be handled by manual tagging.

I'm struggling to put my finger on it, but I feel like there's a reason step 2 might not work for all cases. That said, I can't come up with it, so I may just implement it and see what breaks...

**Comment by sgallagher** [comment]
> > We do have some packages that are built from the `eln` branch (such as `crypto-policies`), so there would be an issue if we re-added the package to the auto-rebuild, but that could be handled by manual tagging.
> 
> I supposed such packages would already be excluded from the "tag the Rawhide build in ELN" automation anyway. Is that assumption wrong?

You are correct; I was postulating above the possibility that a package like that might come back to being built from Rawhide if the divergence was ever eliminated.

> > I'm struggling to put my finger on it, but I feel like there's a reason step 2 might not work for all cases. That said, I can't come up with it, so I may just implement it and see what breaks...
> 
> The only immediate problem I could see is a race condition: If the manual eln build is tagged in eln between steps (2) and (3), the check in (2) will not see it yet, but the tagging in (3) would override it. But even with that, it's better than the status quo. And if desired, is fixable (by checking if this happened after (3)).

Yeah, even after a night of pondering I can't spot what's making me hesitate, so I think I'll just go ahead and make this change.

**Comment by hroncok** [comment]
> I've manually tagged in marshalparser-0.3.4-2.eln126 just now.

3 days later, I still see marshalparser-0.3.4-2.fc39 in ELN:

```
$ koji wait-repo eln-build --build marshalparser-0:0.3.4-2.eln126
nvr marshalparser-0:0.3.4-2.eln126 is not current in tag eln-build
  latest build in eln-build is marshalparser-0.3.4-2.fc39

$ repoquery -q --repo=kojieln marshalparser
marshalparser-0:0.3.4-2.fc39.noarch
``

**Comment by sgallagher** [comment]
Should be fixed now.

`koji wait-repo eln-build --build marshalparser-0.3.4-2.eln126`

**Comment by hroncok** [comment]
Thanks. You closed this as in marshalparser tagged, or as in solution deployed?

**Comment by sgallagher** [comment]
I clicked the wrong button when submitting the comment.

**Comment by hroncok** [comment]
I took a look and it would be hard for me to review it, as I have no idea what the individual functions actually do. Let me know if you want em to dig into that, or if I can leave it to somebody else.

**Comment by sgallagher** [comment]
I don't actually have anyone else to do a review. FWIW, any function in `kojihelpers` is just a wrapper around an XML-RPC call to Koji that returns an object populated from the JSON that Koji sends back.

**Comment by yselkowitz** [comment]
Since the rewrite of EBS, side tags are used, and rawhide builds are never tagged into ELN.
