### ISSUE TITLE
TASK: Fix repo configuration in VM images (or the compose itself?)

### ISSUE THREAD

**Issue by WOnder93** [fedora-eln/eln#123]
### What does the ELN SIG need to do?

The VM images from the ELN compose (I used specifically https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/images/Fedora-ELN-Guest-9.0-0.1681862401.x86_64.qcow2) ship with both `fedora-repos-rawhide` and `fedora-repos-eln` installed and the `rawhide` repo enabled and all `eln-*` repos disabled. It should be the other way around and the `fedora-repos-rawhide` package perhaps shouldn't be installed at all.

I observed a similar issue (`rawhide` repo enabled, shipped `eln-*` repos disabled) also on Fedora ELN systems installed via kickstart+anaconda (internal Beaker machines in Red Hat), though that may or may not be a different issue.

**Comment by sgallagher** [comment]
This should be resolved now. We had accidentally tagged in a `fedora-repos` package from Fedora 38 instead of ELN.

**Comment by WOnder93** [comment]
Indeed it seems to be resolved now, thanks!
