### ISSUE TITLE
TASK: remove tox from buildroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#126]
### What does the ELN SIG need to do?
* tox is unwanted in RHEL.  Therefore, it should be removed from the ELN buildroot preferably before the initial import of c10s.  The exact method of removal will vary, but c9s should be used as a guide.

Current status: https://tiny.distro.builders/view-rpm--view-eln--python3-tox-current-env.html

Many of the listed packages at the Buildroot Levels 2+ are in the process of being removed through other means, so for starters please focus on Required, Dependency, and Buildroot Level 1 packages:

- [x] cargo2rpm: https://src.fedoraproject.org/rpms/cargo2rpm/pull-request/3
- [x] pyparsing
- [x] pyproject-rpm-macros: https://src.fedoraproject.org/rpms/pyproject-rpm-macros/pull-request/386
- [x] python-alembic: https://src.fedoraproject.org/rpms/python-alembic/pull-request/17
- [x] python-bcrypt: being dropped
- [x] python-beautifulsoup4: drop via https://src.fedoraproject.org/rpms/python-lxml/pull-request/25
- [x] python-beniget (dep of pythran): https://src.fedoraproject.org/rpms/python-beniget/pull-request/2
- [x] python-blinker: drop via https://src.fedoraproject.org/rpms/python-oauthlib/pull-request/9
- [x] python-distro: https://src.fedoraproject.org/rpms/python-distro/pull-request/7
- [x] python-gast (dep of pythran): https://src.fedoraproject.org/rpms/python-gast/pull-request/4
- [x] python-iniconfig: https://src.fedoraproject.org/rpms/python-iniconfig/pull-request/3
- [x] python-iniparse: https://src.fedoraproject.org/rpms/python-iniparse/pull-request/5
- [x] python-ptyprocess: https://src.fedoraproject.org/rpms/python-ptyprocess/pull-request/2
- [x] python-qrcode: https://src.fedoraproject.org/rpms/python-qrcode/pull-request/5
- [x] python-ruamel-yaml: https://src.fedoraproject.org/rpms/python-ruamel-yaml/pull-request/12
- [x] python-setuptools_scm: https://src.fedoraproject.org/rpms/python-setuptools_scm/pull-request/20
- [x] python-soupsieve: drop via https://src.fedoraproject.org/rpms/python-lxml/pull-request/25
- [x] python-tomli-w: https://src.fedoraproject.org/rpms/python-tomli-w/pull-request/11
- [x] python-tornado: https://src.fedoraproject.org/rpms/python-tornado/pull-request/11

Relevant Buildroot Level 2 packages:

- [x] python-fixtures: drop via https://src.fedoraproject.org/rpms/python-requests-oauthlib/pull-request/2
- [x] python-u-msgpack-python: drop via https://src.fedoraproject.org/rpms/python-sphinx/pull-request/52 and https://src.fedoraproject.org/rpms/python-sphinxcontrib-htmlhelp/pull-request/5

/cc @hroncok

**Comment by hroncok** [comment]
Most of the packages can be converted from `%pyproject_buildrequires -t` and/or `%tox` to listing the deps differently and executing the tests directly (e.g. via `%pytest`). See for example https://src.fedoraproject.org/rpms/marshalparser/c/89c691e2cf7838acdb2c0b71686e91b975fc94c9?branch=rawhide

pyproject-rpm-macros is an exception, as it actually needs tox inside of the tests. there might be other such cases, but I don't think there will be many.

-----

> python-tornado (both required and unwanted??)

Whoever added it as required should have talked to us and did not. Let them have it, just make sure we don't end up maintaining it.

**Comment by hroncok** [comment]
> pyparsing

This does not pull in tox in dist git. All that is necessary is a rebuild. I kicked off a rawhide one: https://koji.fedoraproject.org/koji/taskinfo?taskID=101491313

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python-tomli-w/pull-request/11

**Comment by yselkowitz** [comment]
> > python-tornado (both required and unwanted??)
> 
> Whoever added it as required should have talked to us and did not. Let them have it, just make sure we don't end up maintaining it.

Looks like it was re-added post 9.0 for the Keylime workload.  Filed https://github.com/minimization/content-resolver-input/pull/825 to fix the status.

**Comment by yselkowitz** [comment]
All Required and Dependency level packages now have PRs.

**Comment by yselkowitz** [comment]
Added Buildroot Level 1 packages to the list, although some may still need to be dropped instead of fixed.

**Comment by hroncok** [comment]
I¨ll work on python-gast and python-setuptools_scm.

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python-setuptools_scm/pull-request/20

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/python-gast/pull-request/4

**Comment by hroncok** [comment]
working on python-beniget

**Comment by yselkowitz** [comment]
@hroncok were you planning on merging your PRs yourself, or should I?

**Comment by hroncok** [comment]
We'll handle it within the team. It's not unusual for PRs to take more than a day to be merged.

**Comment by yselkowitz** [comment]
@hroncok if you could please merge your PRs, a lot of unwanted packages are currently hanging on due to this.

**Comment by hroncok** [comment]
I am waiting for reviews within the team. Why is this suddenly so urgent?

**Comment by hroncok** [comment]
python-beniget has received a review and was merged and built. Others will follow, but note that my peers have more urgent things to review (such as security fixes for Python), so it might take longer than 3 working days to ship those changes.

**Comment by yselkowitz** [comment]
tox is currently the highest-ranked thread by which a whole bunch of unwanted dependencies are hanging on in ELN.  Only by merging and building these can we iterate and see where is the next place we need to focus to get them out of the buildroot.

**Comment by hroncok** [comment]
Reviews received, I am waiting for more CI builds and will merge and build them all.

**Comment by hroncok** [comment]
All PRs should be merged and built in ELN. Let me know if they are not.

**Comment by yselkowitz** [comment]
This package has been removed from the ELN dependency tree.

**Comment by hroncok** [comment]
Oh, here we go again.

https://tiny.distro.builders/view-rpm--view-eln--tox.html

**Comment by hroncok** [comment]
ansible-core has a new depndency on tomcli since https://src.fedoraproject.org/rpms/ansible-core/c/27968f0c938aea34b5d65cfa116f73f247293054?branch=rawhide

tomcli requires https://tiny.distro.builders/view-rpm--view-eln--python3-typer.html

typer requires https://tiny.distro.builders/view-rpm--view-eln--python3-click.html

click requires tox

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/ansible-core/pull-request/48

**Comment by sgallagher** [comment]
@hroncok Thanks for tracking that down!

**Comment by hroncok** [comment]
Apparently, that was not enough. tox is still in, transitively pulled by pytest-xdist, see https://github.com/fedora-eln/eln/issues/125#issuecomment-1746675574

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--tox.html is gone

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--tox.html is back in

apparently, the chain is:

 - [qt6-qtwebengine](https://tiny.distro.builders/view-srpm--view-eln--qt6-qtwebengine.html)
    - BuildRequires [python3-zombie-imp](https://tiny.distro.builders/view-rpm--view-eln--python3-zombie-imp.html) **(unwanted)**
        - uses `%pyproject_buildrequires -t` (and hence BuildRequires tox)

The interesting bit is that qt6-qtwebengine [only BuildRequires python3-zombie-imp `%if %fedora`](https://src.fedoraproject.org/rpms/qt6-qtwebengine/c/90a55c38544e49e9194d6931f8251775a47fcabb) but I suppose that directly causes FTBFS in ELN (there is both `ModuleNotFoundError: No module named 'imp'` and `ModuleNotFoundError: No module named 'six.moves'` in the build.log).

**Comment by hroncok** [comment]
I've opened https://github.com/fedora-eln/eln/issues/163

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--tox.html is gone again for now

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--tox.html is back :cry:

**Comment by hroncok** [comment]
https://src.fedoraproject.org/rpms/openmpi/c/b82bf993d00357a59002dba9ccb81b2d21466c6d?branch=rawhide added a dependency on python3-recommonmark which pulls in the world

**Comment by yselkowitz** [comment]
> https://src.fedoraproject.org/rpms/openmpi/c/b82bf993d00357a59002dba9ccb81b2d21466c6d?branch=rawhide added a dependency on python3-recommonmark which pulls in the world

Already have a PR up: https://src.fedoraproject.org/rpms/openmpi/pull-request/18

**Comment by hroncok** [comment]
@befeleme already opened https://issues.redhat.com/browse/RHEL-15253 in the meantime. I will link your PR there.

**Comment by hroncok** [comment]
tox is again in ELN, but I see https://src.fedoraproject.org/rpms/python-resolvelib/pull-request/3 already opened by @yselkowitz, thanks!

**Comment by hroncok** [comment]
tox might be on its way to ELN, see https://src.fedoraproject.org/rpms/python-cryptography/c/cb16ef22f994a7232a1c9825f4cb99473cfae70d?branch=rawhide (except it doesn't build in eln due to some rust stuff).

**Comment by hroncok** [comment]
I've opened https://bugzilla.redhat.com/show_bug.cgi?id=2295602 for the failure

**Comment by hroncok** [comment]
And https://src.fedoraproject.org/rpms/python-cryptography/pull-request/34 for the tox dependency removal.

**Comment by yselkowitz** [comment]
Thanks @hroncok
