### ISSUE TITLE
TASK: clarify rpmautospec dependencies in RHEL 10

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#127]
### What does the ELN SIG need to do?
* Currently, redhat-rpm-config Requires `rpmautospec-rpm-macros` which provides definitions of `%autorelease` and `%autochangelog` for local builds.  rpmautospec-rpm-macros is part of (but does not require) python-rpmautospec, which also provides a CLI tool for converting spec files as well as a koji builder plugin used to handle this on the builder, both of which use the python library which requires python-koji, which is unwanted in RHEL.
* While the CLI tool will be useful for package maintainers, and the koji builder plugin needed internally somehow for Brew infrastructure, they are not wanted in RHEL either afaics.
* The simplest solution would seemingly be to either add the local macros to redhat-rpm-config and drop the Requires, or provide the macros in a separate SRPM.  EIther way, being a subpackage of python-rpmautospec seems problematic.

**Comment by hroncok** [comment]
If you end up repackaging this thing, please name the package rpmautospec-srpm-macros, to align the name with all the other RPM macros required by  redhat-rpm-config. Thanks.

The scope of this is:

```
$ rpm -ql rpmautospec-rpm-macros
/usr/lib/rpm/macros.d/macros.rpmautospec

$ cat /usr/lib/rpm/macros.d/macros.rpmautospec
%autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = tonumber(rpm.expand("%{?_rpmautospec_release_number}%{!?_rpmautospec_release_number:1}"));
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
%autochangelog %{lua:
    locale = os.setlocale(nil)
    os.setlocale("C.utf8")
    date = os.date("%a %b %d %Y")
    os.setlocale(locale)
    packager = rpm.expand("%{?packager}%{!?packager:John Doe <packager@example.com>}")
    evr = rpm.expand("%{?epoch:%{epoch}:}%{version}-%{release}")
    print("* " .. date .. " " .. packager .. " - " .. evr .. "\\n")
    print("- local build")
}
```

**Comment by yselkowitz** [comment]
In the meantime, filed https://src.fedoraproject.org/rpms/python-rpmautospec/pull-request/4 for the unwanted deps, which should be merged regardless.

**Comment by yselkowitz** [comment]
Filed https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/259

**Comment by yselkowitz** [comment]
PR has been merged; waiting for results to land in ELN.

**Comment by yselkowitz** [comment]
Drop macros subpackage in F40+/RHEL10: https://src.fedoraproject.org/rpms/python-rpmautospec/pull-request/5

**Comment by yselkowitz** [comment]
The macros have been moved from python-rpmautospec/rpmautospec-rpm-macros to redhat-rpm-config in rawhide (F40) and ELN, and python-rpmautospec (along with its koji dependency) has been dropped from ELN.
