### ISSUE TITLE
TASK: remove python-pytest-cov from buildroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#128]
### What does the ELN SIG need to do?
* python-pytest-cov is unwanted in RHEL 10. It should therefore be removed from the ELN buildroot -- either by disabling tests on affected packages (where tests require other unwanted deps), or modifying how pytest is called -- preferably before the initial import of 10.

Current status: https://tiny.distro.builders/view-rpm--view-eln--python3-pytest-cov.html

Many of the listed packages at the Buildroot levels are in the process of being removed through other means, so for starters please focus on Required, Dependency, and Buildroot Level 1 packages:

- [x] python-build: drop via https://github.com/fedora-eln/eln/issues/126
- [x] python-configobj: https://src.fedoraproject.org/rpms/python-configobj/pull-request/4
- [x] python-distro: https://src.fedoraproject.org/rpms/python-distro/pull-request/7
- [x] python-rpmautospec: https://src.fedoraproject.org/rpms/python-rpmautospec/pull-request/4
- [x] python-pytest-timeout: https://src.fedoraproject.org/rpms/python-pytest-timeout/pull-request/2
- [x] python-soupsieve: drop from python-lxml via https://src.fedoraproject.org/rpms/python-lxml/pull-request/25

/cc @hroncok

**Comment by hroncok** [comment]
Using this package is unwnated in Fedora as well, so when getting rid of it, please don't conditionalize on %rhel.

**Comment by hroncok** [comment]
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_linters

**Comment by yselkowitz** [comment]
Unfortunately https://bugzilla.redhat.com/show_bug.cgi?id=2189915 is going to block a new python-lxml build to drop python-soupsieve.

**Comment by yselkowitz** [comment]
This package has been removed from the ELN dependency tree.
