### ISSUE TITLE
TASK: remove python-pytest-randomly from buildroot

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#129]
### What does the ELN SIG need to do?
* python-pytest-randomly was retired from c9s and presumably unwanted (although not explicitly listed as such) in RHEL 10. Therefore, it should be removed from the ELN buildroot preferably before the initial import of c10s. The exact method of removal will vary, but c9s should be used as a guide.

Current status: https://tiny.distro.builders/view-rpm--view-eln--python3-pytest-randomly.html

Many of the listed packages at the deeper buildroot levels are in the process of being removed through other means, so for starters please focus on Buildroot Level 1 or 2 packages (some of which might also be unwanted):

- [x] python-fs: https://src.fedoraproject.org/rpms/python-fs/pull-request/5
- [x] python-time-machine: drop via https://github.com/fedora-eln/eln/issues/126
- [x] python-ufoLib2: https://src.fedoraproject.org/rpms/python-ufoLib2/pull-request/2
- [x] python-virtualenv: drop via https://github.com/fedora-eln/eln/issues/130

/cc @hroncok

**Comment by hroncok** [comment]
The tox removal from python-tomli-w apparently introduced a build dependency on python3-pytest-randomly (the tox usage was broken and brought no test dependencies, run no tests). Will fix that (I also need to get rid of the tomli dependency).

**Comment by hroncok** [comment]
I was wrong, the spec already has a rhel conditional for randomly.

**Comment by yselkowitz** [comment]
This package has been removed from the ELN dependency tree.
