### ISSUE TITLE
TASK: RHEL-like ceph package in ELN

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#135]
### What does the ELN SIG need to do?
* RHEL's ceph package includes only client components: ceph-common, the libraries, and their Python bindings.  However, Fedora's ceph package (and hence that being built currently in ELN) includes all the server components as well.  As a result, a bunch of unwanted dependencies (of the server components) are being pulled into ELN.  However, since ceph is also built in full (with the server components) as part of other products, conditionalizing the server components on `%if %{undefined rhel}` doesn't make sense either, so I think we need an ELN branch.
* For easier maintenance, as a possible first step, a default-on conditional (e.g. `%bcond_without server`) could be added to rawhide to disable the server components if triggered.  Then, in the ELN branch, the only change would be to switch the bcond to default-off (`%bcond_with server`), which should allow rawhide changes to be more easily merged into ELN.
* We would need help from the RHEL ceph maintainers on this, as the changes are extensive and it means maintaining a new branch.  OTOH, since it would only include client bits, perhaps ELN need not be updated quite as frequently as rawhide.
* For reference, client-only conversion in c9s: https://gitlab.com/redhat/centos-stream/rpms/ceph/-/commit/c0f0d39af6ef0e7d0883a5c42b82d1a43a2e21b4

**Comment by sgallagher** [comment]
@kkeithley Can we work with you on this? It's a bit out of our comfort zone.

**Comment by yselkowitz** [comment]
@kkeithley I have a successful client-only ELN scratch build of ceph 18.1.1:

https://koji.fedoraproject.org/koji/taskinfo?taskID=102904613

Whether you want to handle this as a trimming of the full Fedora spec, or as an update to the c9s client-only spec, I can provide the initial PR.  We just need you to request an ELN branch for ceph by `fedpkg request-branch eln --sl rawhide:2099-12-01 --no-auto-module`.

**Comment by kalebskeithley** [comment]
branch requested, send the PR.

**Comment by yselkowitz** [comment]
Filed https://src.fedoraproject.org/rpms/ceph/pull-request/10

**Comment by yselkowitz** [comment]
@kalebskeithley build looks good so far.  But do you know why libradospp-devel is listed in Content Resolver as unwanted?  librbd-devel requires it, and it is shipped in RHEL 9 CRB.

**Comment by yselkowitz** [comment]
@kalebskeithley build looks good so far. But do you know why libradospp-devel is listed in Content Resolver as unwanted? librbd-devel requires it, and it is shipped in RHEL 9 CRB.
