### ISSUE TITLE
TASK: fix remaining ELN workload warnings and errors

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#140]
### What does the ELN SIG need to do?
The following ELN workloads still show warnings/errors and should be fixed.  In some cases that means fixing/updating the CR configs, in other cases it means fixing the packages themselves.

Current status: https://tiny.distro.builders/view-errors--view-eln.html

- [ ] Backup tools from CS System Management SST: `rear` is missing changes from c9s, including `s390x` enablement
- [x] binutils/annobin: `annobin` package has been reorganized, https://github.com/minimization/content-resolver-input/pull/915
- [x] Brasero: `brasero-nautilus` either needs to be updated for `nautilus-extension-4.0`, or if that's not planned, dropped
- [x] CLI tools: `iputils-ninfod` listed but no longer exists, fix via https://github.com/minimization/content-resolver-input/pull/888
- [x] Container tools: typos, fix via https://github.com/minimization/content-resolver-input/pull/929
- [x] Evince: `evince-nautilus` either needs to be updated for `nautilus-extension-4.0`, or if that's not planned, dropped
- [x] Filesystems: `fio-engine-rados` and `fio-engine-rbd` temporarily disabled on ppc64le, fix via https://src.fedoraproject.org/rpms/fio/pull-request/8
- [x] Firewall tools: iptables-nft-services is RHEL specific, fix via https://github.com/minimization/content-resolver-input/pull/872
- [x] Fonts: `ht-caladea-fonts` replaced by `google-crosextra-caladea-fonts`, fix via https://github.com/minimization/content-resolver-input/pull/833 
- [x] fwupd: `fwupd-efi` is only for EFI arches, fix via https://github.com/minimization/content-resolver-input/pull/860
- [x] Go Toolset: golang-race dropped from golang 1.20, fix via https://github.com/minimization/content-resolver-input/pull/929
- [x] HTTP Servers - httpd: `mod_proxy_cluster` is RHEL specific, fix via https://github.com/minimization/content-resolver-input/pull/872
- [x] JMC: retired in Fedora, switch to placeholder, https://github.com/minimization/content-resolver-input/pull/924
- [x] kernel devel/debug: `kernel-debug-uki-virt` is x86_64 specific, fix via https://github.com/minimization/content-resolver-input/pull/888
- [x] LLVM Toolset: no `lld` on `s390x`, no `lld-test` subpackage, fix via https://github.com/minimization/content-resolver-input/pull/862
- [x] lorax template: `smc-meera-fonts` replaced by `rit-meera-new-fonts`, fix via https://github.com/minimization/content-resolver-input/pull/862
- [ ] Mozilla Firefox: `firefox` temporarily not building on `ppc64le`
- [ ] Mozilla Thunderbird: `thunderbird` temporarily not building on `s390x`
- [x] OpenJDK: no `fastdebug` on s390x, fix via https://github.com/minimization/content-resolver-input/pull/862
- [x] openssl: compat-openssl11 not planned for RHEL 10, fix via https://github.com/minimization/content-resolver-input/pull/884
- [x] PCP/Grafana: `pcp-pmda-bpf` should not be listed for `s390x`, fix via https://github.com/minimization/content-resolver-input/pull/888
- [x] Performance Tools: waiting on systemtap rebuild, but also exposed https://src.fedoraproject.org/rpms/systemtap/pull-request/21
- [x] Platform Storage: `boom-boot-grub2` is obsolete, fix via https://github.com/minimization/content-resolver-input/pull/862
- [x] PostgreSQL: split libs from server to avoid libpq-devel/postgresql-server-devel conflict, fix via https://github.com/minimization/content-resolver-input/pull/872
- [x] CS System management: `opal-firmware` no longer built, https://github.com/minimization/content-resolver-input/pull/932
- [x] Virt KVM Userspace: `libguestfs-winsupport` is RHEL specific and `sgabios` retired, fix via https://github.com/minimization/content-resolver-input/pull/888
- [x] X11 Server: `xorg-x11-drv-v4l` was retired (orphaned 6+ weeks), drop via https://github.com/minimization/content-resolver-input/pull/933

Some individual placeholders or packages also have warnings:

- [ ] at: suggest postfix for `smtpdaemon`, https://src.fedoraproject.org/rpms/fedora-release/pull-request/268
- [x] ibus-typing-booster: switch to hunspell backend, https://src.fedoraproject.org/rpms/ibus-typing-booster/pull-request/38
- [x] mingw-qemu-ga-win: no msitools on s390x, fix via https://github.com/minimization/content-resolver-input/pull/929
- [ ] php: suggest postfix for `smptdaemon`, https://src.fedoraproject.org/rpms/fedora-release/pull-request/268
- [x] realtime-setup: `annobin` reorganization, but can be a real package now: https://github.com/minimization/content-resolver-input/pull/915
- [x] virtio-win: obsolete mingw dependencies, fix via https://github.com/minimization/content-resolver-input/pull/929

**Comment by yselkowitz** [comment]
@tpopela pursuant to the above, it looks like there are upstream PRs to update (thereby allowing re-enablement of) brasero-nautilus and evince-nautilus:

https://gitlab.gnome.org/GNOME/brasero/-/merge_requests/21
https://gitlab.gnome.org/GNOME/evince/-/merge_requests/561

Are these expected to get in so as to restore these disabled subpackages?

**Comment by tpopela** [comment]
@yselkowitz I will temporarily comment out both as they will first need at least a review upstream before we can backport them (and with Evince we have to wait for its GTK 4 port to be finished and released which will happen in August).

**Comment by yselkowitz** [comment]
The remaining issues are in the packages themselves rather than CR issues or fedora-release Suggests, and the maintainers of those packages should be on top of those.
