### ISSUE TITLE
Fedora-ELN-20230630.2 fails to install (conflict between libdnf5 and dnf-data)

### ISSUE THREAD

**Issue by AdamWill** [fedora-eln/eln#143]
Fedora-ELN-20230630.2 fails to install, it crashes early in the install process. anaconda.log shows:

    pyanaconda.modules.common.errors.general.AnacondaError: The transaction process has ended abruptly: Transaction test error:
      file /etc/dnf/dnf.conf conflicts between attempted installs of libdnf5-5.0.14-2.fc39.x86_64 and dnf-data-4.16.1-2.eln127.noarch
    Traceback (most recent call last):
      File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/payloads/payload/dnf/dnf_manager.py", line 708, in _run_transaction
        base.do_transaction(display)
      File "/usr/lib/python3.11/site-packages/dnf/base.py", line 1009, in do_transaction
        raise dnf.exceptions.Error(errstring)
    dnf.exceptions.Error: Transaction test error:
      file /etc/dnf/dnf.conf conflicts between attempted installs of libdnf5-5.0.14-2.fc39.x86_64 and dnf-data-4.16.1-2.eln127.noarch

**Comment by sgallagher** [comment]
Looks like the issue is here:

```	
%if 0%{?fedora} <= 38
Requires:       dnf-data
%endif
```

Which of course parses as `%if 0 <= 38` on ELN

**Comment by AdamWill** [comment]
Not sure if .3 was meant to fix this, but it doesn't.

**Comment by sgallagher** [comment]
No, the situation is pretty broken. I've submitted https://github.com/rpm-software-management/dnf5/pull/691 as a *start* to getting to a solution, but I really need the DNF5 folks to step up here.

**Comment by yselkowitz** [comment]
All set now?

**Comment by yselkowitz** [comment]
This was fixed some time ago.
