### ISSUE TITLE
TASK: drop unwanted packages from ELN runtime

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#146]
### What does the ELN SIG need to do?
A number of packages currently marked as unwanted currently remain in the ELN runtime (required or dependency levels).  Their status needs to be clarified, and if truly unwanted (rather than just needing a new maintainer), removed from the dependency tree.

Complete list: https://tiny.distro.builders/view-unwanted--view-eln.html

- [x] aopappliance: dependency of `google-guice`
- [x] clang16, llvm16: rebuild of dependent packages needed, providing no API breakage has occurred
- [x] clutter, clutter-gst3, clutter-gtk, cogl: dependencies of `cheese`; sst_desktop is tracking
- [ ] dbus-glib: dependency of `firefox`, `thermald`, and `thunderbird`; sst_desktop is tracking
- [ ] ed: dependency of `cscope` and `patch`, BR of `bc`, `mksh`, `Xaw3d`
- [x] fmt: dependency of ~~`dnf5`,~~ `paps` and `spdlog`.  Drop from runtime via https://src.fedoraproject.org/rpms/paps/pull-request/1
- [ ] fxload: dependency of `alsa-tools-firmware`, present in c9s
- [x] gsl: dependency of `bogofilter`, present in c9s
- [x] gtk2: dependency of `xsane` (other dependents were either ported to gtk3 or dropped); sst_desktop is tracking
- [x] infinipath-psm: dep of openmpi, drop via https://src.fedoraproject.org/rpms/openmpi/pull-request/12 and https://src.fedoraproject.org/rpms/mpich/pull-request/9
- [x] java-1.8.0-openjdk: https://github.com/fedora-eln/eln/issues/155
- [x] java-11-openjdk: https://github.com/fedora-eln/eln/issues/155
- [x] koji: drop via https://github.com/minimization/content-resolver-input/pull/958 and https://github.com/fedora-eln/eln/issues/127
- [ ] libdb: https://github.com/fedora-eln/eln/issues/154
- [x] libdbusmenu: new dependency of ibus, drop via https://src.fedoraproject.org/rpms/ibus/pull-request/34
- [x] libicu72: should drop after F39 mass rebuild
- [x] libpsm2: drop via https://src.fedoraproject.org/rpms/libfabric/pull-request/1 and https://src.fedoraproject.org/rpms/openmpi/pull-request/13
- [ ] libradospp-devel: subpackage of `ceph`, dependency of `librdb-devel`, why unwanted?
- [ ] libsamplerate: dependency of `alsa-plugins`, `alsa-utils`, present in c9s
- [x] libsoup: https://github.com/fedora-eln/eln/issues/148
- [x] libunwind: drop via https://src.fedoraproject.org/rpms/sysprof/pull-request/4, and dropping nvml from qemu-kvm
- [x] libvncserver: bundled in RHEL gnome-remote-desktop
- [x] libxklavier: dependency of `anaconda` (although probably not after the web-based overhaul) and `libgnomekbd` (being replaced by `tecla`
- [x] linuxconsoletools: dependency of `gpm`, present in c9s
- [ ] mtools: dependency of several packages, present in c9s
- [x] nvml (libpmem): drop via https://src.fedoraproject.org/rpms/qemu/pull-request/44
- [ ] openssl-pkcs11: replaced by pkcs11-provider, see https://github.com/minimization/content-resolver-input/pull/886
- [ ] openwsman-python3: dependency of `fence-agents-amt-ws`, present in c9s
- [ ] pcp-pmda-gfs2 (aarch64 only)
- [x] pcre: https://github.com/fedora-eln/eln/issues/147
- [ ] perl-IO-Socket-INET6
- [ ] perl-Socket6
- [x] python3.11: drop via https://github.com/fedora-eln/eln/issues/144 and fixes for 3.12 also needed for firefox and thunderbird
- [x] python-ethtool: drop via https://github.com/minimization/content-resolver-input/pull/935 and downstreaming of https://github.com/candlepin/subscription-manager/pull/3284
- [x] python-qt5: sst_desktop is tracking
- [x] qt5-*: sst_desktop is tracking
- [ ] rtkit
- [x] tbb
- [x] tomcat - wanted after all

**Comment by hroncok** [comment]
> The package python3-ethtool will be deprecated in RHEL 10+ and ELN

Glad to see that finally happening. It's still required by [subscription-manager](https://tiny.distro.builders/view-rpm--view-eln--subscription-manager.html).

**Comment by yselkowitz** [comment]
> Glad to see that finally happening. It's still required by [subscription-manager](https://tiny.distro.builders/view-rpm--view-eln--subscription-manager.html).

Dropped in today's 1.29.36.

**Comment by mizdebsk** [comment]
aopalliance is no longer unwanted; see https://github.com/minimization/content-resolver-input/pull/959

**Comment by yselkowitz** [comment]
At this point, we should track removals (and additions) in c10s and implement them in ELN accordingly; closing.
