### ISSUE TITLE
Rebuid of the selinux update needs to be done in a specific order

### ISSUE THREAD

**Issue by bookwar** [fedora-eln/eln#15]
https://bodhi.fedoraproject.org/updates/FEDORA-2020-44f878be7e

libsepol -> libselinux -> libsemanage -> poliycoreutils -> setools -> checkpolicy -> selinux-policy -> shadow-utils -> sssd

**Comment by bookwar** [comment]
We already have built sssd-2.4.0-3.eln105 while the libraries it links to were not updated in the buildroot

**Comment by bookwar** [comment]
We got libsepol and libselinux updated.

I've rebuilt the libsemanage but Bodhi is stuck on signing it.

**Comment by bookwar** [comment]
Libraries landed. shadow-utils and sssd need a rebuild

**Comment by bachradsusi** [comment]
I'd like to drop libsepol-compat and libsemanage-compat as soon as possible as they have some issues with affects tests. But I can't before shadow-utils is rebuilt

**Comment by bachradsusi** [comment]
https://koji.fedoraproject.org/koji/packageinfo?packageID=487 shadow-utils is rebuilt
