### ISSUE TITLE
TASK: drop java-1.8.0-openjdk, java-11-openjdk from ELN

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#155]
### What does the ELN SIG need to do?
OpenJDK 1.8 and 11 have been declared unwanted in ELN.  Currently, OpenJDK 17 is the default and all packages should use it both at build and runtime.  OpenJDK 21 will eventually land too as an option, but when it will become the default in Fedora (much less in RHEL) has not been stated yet.

Our RPM macros create a (1.8.0 or 11 or 17) dependency which confuses CR, so provide it some guidance to use the preferred version:

Status: https://tiny.distro.builders/view-rpm--view-eln--java-1.8.0-openjdk-headless.html and https://tiny.distro.builders/view-rpm--view-eln--java-11-openjdk-headless.html

- [x] fedora-release: https://src.fedoraproject.org/rpms/fedora-release/pull-request/266

These build with `java-11-openjdk-devel` explicitly, but from back when 1.8.0 was still the default, and should now use the default:

Status: https://tiny.distro.builders/view-rpm--view-eln--java-11-openjdk-devel.html

- [x] byteman: https://src.fedoraproject.org/rpms/byteman/pull-request/3
- [x] ecj: https://src.fedoraproject.org/rpms/ecj/pull-request/1

These build with `java-1.8.0-openjdk-devel` explicitly, and need to be ported (in packaging, and maybe in code too) to build with default `java-devel`:

Status: https://tiny.distro.builders/view-rpm--view-eln--java-1.8.0-openjdk-devel.html

- [x] crypto-policies: https://src.fedoraproject.org/rpms/crypto-policies/pull-request/11 and https://gitlab.com/redhat/centos-stream/rpms/crypto-policies/-/merge_requests/22
- [x] tzdata: https://src.fedoraproject.org/rpms/tzdata/pull-request/15
- [x] xerces-j2: https://src.fedoraproject.org/rpms/xerces-j2/pull-request/7

These build with `maven-local-openjdk8`, and need to be ported (in packaging, and maybe in code too) to build with default `maven-local`:

Status: https://tiny.distro.builders/view-rpm--view-eln--maven-local-openjdk8.html

- [x] apache-commons-codec
- [x] apache-commons-io
- [x] apache-commons-lang3
- [x] google-guice
- [x] guava
- [x] httpcomponents-client
- [x] httpcomponents-core
- [x] jctools
- [x] jsr-305
- [x] maven
- [x] maven-resolver
- [x] maven-shared-utils
- [x] maven-wagon
- [x] plexus-cipher
- [x] plexus-classworlds
- [x] plexus-containers
- [x] plexus-interpolation
- [x] plexus-io
- [x] plexus-sec-dispatcher
- [x] sisu
- [x] slf4j

**Comment by mizdebsk** [comment]
I will port ELN packages from maven-local-openjdk8 to maven-local myself.
I already have a work in progress for this.
For now I have no plans of porting non-ELN Fedora packages using maven-local-openjdk8, if there are any.

**Comment by mizdebsk** [comment]
Pull requests for aforementioned packages:
* apache-commons-codec [PR](https://src.fedoraproject.org/rpms/apache-commons-codec/pull-request/2)
* apache-commons-io [PR](https://src.fedoraproject.org/rpms/apache-commons-io/pull-request/5)
* apache-commons-lang3 [PR](https://src.fedoraproject.org/rpms/apache-commons-lang3/pull-request/6)
* google-guice [PR](https://src.fedoraproject.org/rpms/google-guice/pull-request/6)
* guava [PR](https://src.fedoraproject.org/rpms/guava/pull-request/5)
* httpcomponents-client [PR](https://src.fedoraproject.org/rpms/httpcomponents-client/pull-request/5)
* httpcomponents-core [PR](https://src.fedoraproject.org/rpms/httpcomponents-core/pull-request/2)
* jctools [PR](https://src.fedoraproject.org/rpms/jctools/pull-request/9)
* jsr-305 [PR](https://src.fedoraproject.org/rpms/jsr-305/pull-request/1)
* maven [PR](https://src.fedoraproject.org/rpms/maven/pull-request/50)
* maven-resolver [PR](https://src.fedoraproject.org/rpms/maven-resolver/pull-request/12)
* maven-shared-utils [PR](https://src.fedoraproject.org/rpms/maven-shared-utils/pull-request/4)
* maven-wagon [PR](https://src.fedoraproject.org/rpms/maven-wagon/pull-request/9)
* plexus-cipher [PR](https://src.fedoraproject.org/rpms/plexus-cipher/pull-request/8)
* plexus-classworlds [PR](https://src.fedoraproject.org/rpms/plexus-classworlds/pull-request/4)
* plexus-containers [PR](https://src.fedoraproject.org/rpms/plexus-containers/pull-request/5)
* plexus-interpolation [PR](https://src.fedoraproject.org/rpms/plexus-interpolation/pull-request/3)
* plexus-io [PR](https://src.fedoraproject.org/rpms/plexus-io/pull-request/4)
* plexus-sec-dispatcher [PR](https://src.fedoraproject.org/rpms/plexus-sec-dispatcher/pull-request/2)
* sisu [PR](https://src.fedoraproject.org/rpms/sisu/pull-request/4)
* slf4j [PR](https://src.fedoraproject.org/rpms/slf4j/pull-request/12)

**Comment by mizdebsk** [comment]
All pull requests were merged.

**Comment by mizdebsk** [comment]
tzdata PR looks good to me, but I'm not too familiar with the package - I'd let maintainers review and merge it.

**Comment by yselkowitz** [comment]
Thanks, are you aware of any use for the pre-1.8 javazi nowadays?

**Comment by mizdebsk** [comment]
> Thanks, are you aware of any use for the pre-1.8 javazi nowadays?

No. And I think that Java < 8 support can be dropped even in rawhide, not only in ELN.

**Comment by yselkowitz** [comment]
All ELN packages now use java-17-openjdk to build, and 1.8.0 and 11 have been completely dropped from ELN.  Thank you @mizdebsk for your help with this!
