### ISSUE TITLE
ELN-Extras content does not belong in the main ELN compose variants

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#156]
### What does the ELN SIG need to do?

See https://github.com/minimization/content-resolver/issues/48

Please, remove python3-toml and python3-pytz from ELN. Neither of them is in the content resolver:

 - https://tiny.distro.builders/view-rpm--view-eln--python3-pytz.html 404
 - https://tiny.distro.builders/view-rpm--view-eln--python3-toml.html 404

But both are in https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/AppStream/x86_64/os/Packages/

The components are still being built in ELN:

 - [pytz](https://koji.fedoraproject.org/koji/packageinfo?packageID=3669)
 - [python-toml](https://koji.fedoraproject.org/koji/packageinfo?packageID=20597)

Most importantly, please figure out if there are more packages like this. We don't want packages imported to RHEL 10 if nothing pulls them in.

**Comment by sgallagher** [comment]
These are coming in because of ELN-Extras: See

- https://tiny.distro.builders/view-rpm--view-eln-extras--python3-pytz.html
- https://tiny.distro.builders/view-rpm--view-eln-extras--python3-toml.html

But you're right, they shouldn't be ending up in the AppStream repo compose; I'll look into separating ELN-Extras content into its own Variant.

**Comment by sgallagher** [comment]
Addendum: Despite their presence in the ELN compose, they won't be imported into CentOS Stream 10 or RHEL 10 so long as they're not in the `eln` view of Content Resolver.

**Comment by hroncok** [comment]
Isn't ELN extras a separate repo?

**Comment by sgallagher** [comment]
> Isn't ELN extras a separate repo?

Yes, so something is wrong with the tools that split them. I'm looking into it.

**Comment by sgallagher** [comment]
I've cleaned up the `prepopulate.json` from `pungi-fedora` and removed entries in there that are no longer in ELN. This seems to have done the job. We need a long-term solution for properly maintaining that file which we're working on, but for now this will have to do.

**Comment by hroncok** [comment]
Thanks.
