### ISSUE TITLE
TASK: check distribution-gpg-keys build automation

### ISSUE THREAD

**Issue by sandrobonazzola** [fedora-eln/eln#159]
### What does the ELN SIG need to do?
* check distribution-gpg-keys build automation:

distribution-gpg-keys is shipped in ELN-Extra as well as mock. But trying to install mock on ELN ends up with:

```console
# dnf install mock
Last metadata expiration check: 0:13:10 ago on Wed Sep 27 15:04:21 2023.
Error: 
 Problem: package mock-5.1-1.eln130.noarch from eln-extras requires mock-configs, but none of the providers can be installed
  - conflicting requests
  - nothing provides distribution-gpg-keys >= 1.96 needed by mock-core-configs-39.1-1.eln130.noarch from eln-extras
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

checking https://koji.fedoraproject.org/koji/packageinfo?packageID=21232 shows distribution-gpg-keys is not being rebuilt for eln in a while.

**Comment by sgallagher** [comment]
We were having issues with the sync tool for much of September and this is one we missed. The automation was fixed recently and I've kicked off a [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=106789170) of distribution-gpg-keys manually.
