### ISSUE TITLE
Generate s390x/ppc64le/arm64 container images for eln

### ISSUE THREAD

**Issue by mh21** [fedora-eln/eln#16]
The Red Hat CKI team (https://cki-project.org/) would like to run kernel tests for ELN on arches other than x64. For that, we need to build a container image derived from fedora:eln for s390x/ppc64le/arm64.

At the moment, the eln container image at https://quay.io/repository/fedoraci/fedora?tab=tags is only available for x64. In koji (https://koji.fedoraproject.org/koji/packageinfo?packageID=26387), fedora-container-base-ELN is also only built for x64, while eg -Rawhide has all the arches.

The sync script at https://pagure.io/fedora-ci/eln-upload-container-images/blob/master/f/sync-latest-container-base-image.sh therefore (?) also only syncs x64 to quay.io.

@sgallagher, would it be possible to extend the eln container image to the other arches? Otherwise it is impossible for the CKI team to build eln kernels for testing 😕.

**Comment by mh21** [comment]
This has also been filed at https://pagure.io/releng/issue/9852. I asked on #fedora-releng and the recommendation was to file a ticket here.

**Comment by sgallagher** [comment]
I believe https://pagure.io/pungi-fedora/pull-request/937 should address this.

**Comment by hanzz** [comment]
Just a note for me for tomorrow. We also need to update https://pagure.io/fedora-ci/eln-upload-container-images/blob/master/f/sync-latest-container-base-image.sh so it uploads the images for other arches to quay.io

**Comment by mh21** [comment]
Hi @hanzz, I created https://pagure.io/fedora-ci/eln-upload-container-images/pull-request/1 for the sync script.

At the moment, it will not work as the s390x build is unhappy (https://koji.fedoraproject.org/koji/taskinfo?taskID=56229112). Is there anything we can help to move it along?

**Comment by hanzz** [comment]
sssd package needs to be rebuilt in "eln" Koji tag (or in rawhide to propagate it to eln koji tag) against newer libsemanage.so.2. @sgallagher  can do that, but there is thanksgiving so most of the US people are on holiday.

**Comment by hanzz** [comment]
Hm, checking the logs that's probably different issue.

**Comment by hanzz** [comment]
It seems this is not directly related to Fedora ELN. Recent Fedora Rawhide images fail the very same way on s390x.

**Comment by hanzz** [comment]
Looks like some issue with anaconda. It seems the anaconda did not start on s390x in rawhide when building it. You can try to follow-up with anaconda people. I'm away for the weekend now.

**Comment by contyk** [comment]
@hanzz There was a thread about broken s390x buildroots on the devel thread; I didn't pay much attention to it but it's likely related.

**Comment by sgallagher** [comment]
Bump. We need to revisit this.

**Comment by mh21** [comment]
@hanzz, @sgallagher, looking at [koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=26387) again, [rawhide](https://koji.fedoraproject.org/koji/buildinfo?buildID=1825273) is again able to build s390x images, but [eln](https://koji.fedoraproject.org/koji/buildinfo?buildID=1826036) still has them disabled. Would it be possible to reenable s390x container images for eln now that anaconda seems fixed?

**Comment by sgallagher** [comment]
@mh21 https://pagure.io/pungi-fedora/pull-request/1041

**Comment by sgallagher** [comment]
https://pagure.io/pungi-fedora/pull-request/1041 has been merged, so the next compose will attempt to build them again. If it fails, I'll revert the change.

**Comment by sgallagher** [comment]
For the record, this ticket is blocked, pending the availability of z14 hardware in Fedora.

**Comment by sgallagher** [comment]
As of 2021-02-01, the s390x containers are also being generated for ELN.

**Comment by mh21** [comment]
@sgallagher the multi-arch manifest at https://quay.io/repository/fedoraci/fedora&tab=tags still doesn't include s390x 😕

**Comment by mh21** [comment]
@sgallagher trying to install anything inside of the container image fails similar to 

```
$ podman run -it --rm quay.io/fedoraci/fedora:eln
# dnf update -y ca-certificates
Fedora - ELN BaseOS - Developmental packages for the next Enterpri 636 kB/s | 959 kB     00:01    
Fedora - ELN AppStream - Developmental packages for the next Enter 2.2 MB/s | 6.4 MB     00:02    
Last metadata expiration check: 0:00:01 ago on Thu Dec  9 09:52:14 2021.
Dependencies resolved.
===================================================================================================
 Package                  Architecture    Version                        Repository           Size
===================================================================================================
Upgrading:
 ca-certificates          noarch          2021.2.50-5.eln114             eln-baseos          353 k

Transaction Summary
===================================================================================================
Upgrade  1 Package

Total download size: 353 k
Downloading Packages:
ca-certificates-2021.2.50-5.eln114.noarch.rpm                      366 kB/s | 353 kB     00:00    
---------------------------------------------------------------------------------------------------
Total                                                              366 kB/s | 353 kB     00:00     
Fedora - ELN BaseOS - Developmental packages for the next Enterpri 1.6 MB/s | 1.6 kB     00:00    
GPG key at file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-eln-x86_64 (0x38AB71F4) is already installed
The GPG keys listed for the "Fedora - ELN BaseOS - Developmental packages for the next Enterprise Linux release" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: ca-certificates-2021.2.50-5.eln114.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-eln-x86_64
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by sgallagher** [comment]
@hanzz Can you look into adding the s390x container to the multi-arch manifest?


Regarding the GPG key issue, that's entirely unrelated. Please open a new bug about that.

**Comment by mh21** [comment]
@sgallagher yeah we never bothered to use the upstream images and just created our own eln container image from scratch 🤦. Issue about the GPG keys created as https://github.com/fedora-eln/eln/issues/77.
