### ISSUE TITLE
TASK: check docs pointing to unreachable status page

### ISSUE THREAD

**Issue by sandrobonazzola** [fedora-eln/eln#160]
### What does the ELN SIG need to do?
* check https://docs.fedoraproject.org/en-US/eln/extras/ as it points to http://distrobuildsync-eln-ops.apps.stream.rdu2.redhat.com/status which is unreachable

**Comment by sgallagher** [comment]
That link is indeed available only behind the firewall. There’s a public
mirror at https://sgallagh.fedorapeople.org/dbs_status.html

I’ll see about getting that link updated.

**Comment by sgallagher** [comment]
This has been fixed. Thanks for the report.
