### ISSUE TITLE
TASK: newly added pkg `gi-docgen` not showing up in Extras

### ISSUE THREAD

**Issue by sandrobonazzola** [fedora-eln/eln#161]
### What does the ELN SIG need to do?
* please check why newly added pkg `gi-docgen` ( https://github.com/minimization/content-resolver-input/pull/985) is not showing up in Extras latest compose: ( https://odcs.fedoraproject.org/composes/production/Fedora-ELN-20230929.1/compose/Extras/source/tree/Packages/ )

**Comment by sgallagher** [comment]
I think I know what's happening here. The ELN-Extras compose explicitly excludes any package that appears in the ELN package set. However, this particular package is only included in the buildroot, not the public compose of ELN. I'll see what I can do about that.

**Comment by sgallagher** [comment]
My original guess was incorrect, but I think I've tracked it down to a mistake in the way we generate comps.xml.

https://pagure.io/fork/sgallagh/fedora-comps/diff/main..eln-fixes

**Comment by sgallagher** [comment]
I see it at https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Extras/x86_64/os/Packages/ now, so the fix seems to have worked. Thanks for the report!

**Comment by sandrobonazzola** [comment]
Thanks for fixing :-)
