### ISSUE TITLE
TASK: python-pyqt6-6.5.2-3.fc40  in ELN brings in qt6-qtwebengine, python3-zombie-imp, tox, everything

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#163]
Investigating https://github.com/fedora-eln/eln/issues/126#issuecomment-1752859629 I *think* that the only reason for qt6-qtwebengine to be in ELN, is the Fedora/EPEL-only conditional dependency in python-pyqt6: https://src.fedoraproject.org/rpms/python-pyqt6/c/8bfa91ad6b128cca3a9be9b3def2f19e1f500704?branch=rawhide

The latest build of  python-pyqt6 in ELN is from Rawhide, hence the dependency is *enabled*. The build happened (and was pushed stable) 4 days ago, yet there was no automatic ELN rebuild.

To fix this, python-pyqt6 needs to be built in ELN. I have the power to do that, but there seems to be a bug in automation that I do not want to hide.

**Comment by sgallagher** [comment]
I don't know why the automation missed it (nothing related in the logs that I can find). I've instructed the rebuilder to pick it up and build it.

**Comment by hroncok** [comment]
Thanks.
