### ISSUE TITLE
TASK: Please provide up2date Fedora ELN container image

### ISSUE THREAD

**Issue by praiskup** [fedora-eln/eln#164]
### What does the ELN SIG need to do?
* build container (Podman) images periodically to allow the use of Mock with "bootstrap  image" for fedora-eln-* chroots

**Comment by praiskup** [comment]
Some docs about why we are using Bootstrap images by default:
https://rpm-software-management.github.io/mock/Feature-container-for-bootstrap
https://rpm-software-management.github.io/mock/Feature-bootstrap

**Comment by praiskup** [comment]
Nice!  Do we have documentation for it or some project page at least?  It would be nice to rely on something "official", so we can be calm that the reference will not stale.

**Comment by praiskup** [comment]
> Is there something special that a bootstrap image needs

It absolutely needs DNF, but it is there.  Things would build be much faster if `python3-dnf-plugins-core` was present, too.  Do you think it could be added?

**Comment by sgallagher** [comment]
> Nice! Do we have documentation for it or some project page at least? It would be nice to rely on something "official", so we can be calm that the reference will not stale.

https://docs.fedoraproject.org/en-US/eln/deliverables/#_container_image

**Comment by praiskup** [comment]
Thanks, @sgallagher!

I submitted a separate ticket #166 for my previous question and closing!
