### ISSUE TITLE
python-urllib3-1.26.17-2.fc40 not tagged into ELN, not rebuilt in ELN

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#167]
Yesterday,
I've built python-urllib3-1.26.17-2.fc40 in rawhide. The update went stable 13 hours ago.

https://bodhi.fedoraproject.org/updates/FEDORA-2023-5309ba4d5e

The build https://koji.fedoraproject.org/koji/buildinfo?buildID=2305294 is tagged into f40.

It was not tagged to ELN. It was not rebuilt in ELN. I suppose something is stuck... ?

**Comment by sgallagher** [comment]
I just looked and it built in ELN just fine, but it took a while to start. This usually means that the previous batch it was processing had one or more packages that takes a long time to build. A couple months ago, we changed how our rebuilds work; I really need to write up a blog post explaining the situation. In some situations (like this) it can result in a much longer wait for the ELN build. The upside is that builds are FAR more likely to succeed and it also resolves an issue with triggering builds in CentOS Stream 10.

**Comment by hroncok** [comment]
It seems to have been built in eln-build-side-75472 but so far no Bodhi update happened. Is that also expected with the new approach?

**Comment by sgallagher** [comment]
Yes, batches all take place in a side tag and will get tagged in once all packages in that side tag are done rebuilding. The current batch is fairly large because the previous batch took so long. See the contents of that tag for what has succeeded or not. It will get tagged in automatically when it completes.

**Comment by sgallagher** [comment]
Looking at the logs, the previous batch included `gcc` which is why `python-urllib3` was queued for so long.

**Comment by hroncok** [comment]
Thanks for the explnation.

**Comment by sgallagher** [comment]
https://sgallagh.wordpress.com/2023/10/13/sausage-factory-fedora-eln-rebuild-strategy/
