### ISSUE TITLE
TASK: cython is missing from CRB

### ISSUE THREAD

**Issue by davide125** [fedora-eln/eln#168]
It looks like cython isn't available, despite being included in `sst_cs_apps-python-crb.yaml` (which means it should be available in CRB). See https://download.copr.fedorainfracloud.org/results/@meta/pystemd/fedora-eln-x86_64/06543954-python-pystemd/builder-live.log.gz for an example failure.

**Comment by sgallagher** [comment]
https://pagure.io/pungi-fedora/pull-request/1215
