### ISSUE TITLE
TASK: s390x failures for ELN Extras Meta workload

### ISSUE THREAD

**Issue by davide125** [fedora-eln/eln#170]
### What does the ELN SIG need to do?
We need some help debugging the failure in https://tiny.distro.builders/workload--eln_extras_meta--fedora-empty-base--repository-fedora-eln--s390x.html

```
 Problem: conflicting requests
  - nothing provides python3.12dist(awscrt) >= 0.16.4 needed by awscli2-2.13.28-1.eln132.noarch
```

The awscli2 package was never included in s390x in this workload, and was completely removed in https://github.com/minimization/content-resolver-input/commit/d69ede786241ae406be6c0e3fbc5d32e6645e694 as it was added in ELN proper, so I'm not sure why this is still failing, and I don't know how to debug it further.

**Comment by osandov** [comment]
This is causing Packit to fail for drgn on fedora-eln-s390x, because the drgn build requires libkdumpfile-devel, which comes from the ELN Extras Meta workload.

**Comment by yselkowitz** [comment]
@davide125 @osandov is this still an issue for either of you?

**Comment by osandov** [comment]
I think it's fixed now: https://tiny.distro.builders/workload--eln_extras_meta--base-eln-extras--repository-fedora-eln-extras--s390x.html.
