### ISSUE TITLE
TASK: Make the current ELN container build

### ISSUE THREAD

**Issue by pablomh** [fedora-eln/eln#173]
### What does the ELN SIG need to do?
* Make the current ELN container build

The existing one (2024-01-15) doesn't build:

```
$ podman run -it --rm quay.io/fedoraci/fedora:eln
ERRO[0000] running `/usr/bin/newuidmap 104622 0 1000 1 1 524288 65536`: newuidmap: write to uid_map failed: Operation not permitted 
Error: cannot set up namespace using "/usr/bin/newuidmap": should have setuid or have filecaps setuid: exit status 1
```

**Comment by sgallagher** [comment]
That error is coming from podman. It looks like your user namespace configuration is broken somehow.

I can't reproduce this on my Fedora 39 system with Podman 4.8.3.

**Comment by pablomh** [comment]
Thanks for taking a look. I'll close it then.
