### ISSUE TITLE
TASK: Fix F40FTBFS from ELN package set

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#176]
### What does the ELN SIG need to do?
* The F40 mass rebuild is going to have a number of FTBFS, with GCC 14 changes being the primary culprit. Any failures in the ELN package set will need to be fixed promptly, as the CentOS Stream 10 import is imminent and we need all packages to be buildable.

List of all F40FTBFS (although our focus is only on the ELN package set): https://kojipkgs.fedoraproject.org/mass-rebuild/f40-failures.html

- [x] apache-commons-exec
- [x] apache-commons-jxpath
- [x] asio
- [x] atlas
- [x] bcc
- [x] brasero
- [x] capstone
- [x] ceph
- [x] chrony
- [x] cmake
- [x] colord
- [x] curl: https://src.fedoraproject.org/rpms/python-impacket/pull-request/6
- [x] delve
- [x] dnf
- [x] dpdk: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113572
- [x] elfutils
- [x] exfatprogs
- [x] fcoe-utils
- [x] fftw
- [x] freerdp
- [x] freetype
- [x] fuse-overlayfs
- [x] galera
- [x] gdb
- [x] ghostscript
- [x] gjs
- [x] glib2
- [x] glibc
- [x] gnome-font-viewer
- [x] gnome-keyring: https://src.fedoraproject.org/rpms/gnome-keyring/pull-request/11
- [x] gnu-efi: https://src.fedoraproject.org/rpms/gnu-efi/pull-request/4
- [x] gnutls
- [x] gtk-doc
- [x] gtk4
- [x] hunspell
- [x] ibus-anthy: https://fedoraproject.org/wiki/Changes/ibus-anthy_1.5.16
- [x] ibus-libpinyin
- [x] ibus-typing-booster
- [x] iproute
- [x] ipxe
- [x] jose
- [x] jq
- [x] json-c
- [x] kasumi
- [x] kernelshark
- [x] kexec-tools
- [x] keylime-agent-rust
- [x] lasso
- [x] ldns
- [x] ledmon: https://src.fedoraproject.org/rpms/ledmon/pull-request/4
- [x] libXext
- [x] libcomps
- [x] libecpg: https://src.fedoraproject.org/rpms/libecpg/pull-request/10
- [x] libfabric
- [x] libgee
- [x] libgit2
- [x] libgphoto2
- [x] libguestfs
- [x] libjpeg-turbo: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113485
- [x] libmemcached-awesome
- [x] libmodulemd: https://src.fedoraproject.org/rpms/libmodulemd/pull-request/36
- [x] libnxz: https://github.com/libnxz/power-gzip/issues/207
- [x] libpfm: https://src.fedoraproject.org/rpms/libpfm/pull-request/7
- [x] libreport
- [x] libseccomp
- [x] libsigc++20
- [x] libsmi
- [x] libsrtp
- [x] libtasn1
- [x] libtool
- [x] libunwind
- [x] libuv
- [x] libwebp
- [x] libxkbcommon
- [x] llvm
- [x] mod_proxy_cluster
- [x] mozjs115
- [x] mpich
- [x] msitools: https://src.fedoraproject.org/rpms/msitools/pull-request/5
- [x] net-snmp
- [x] netpbm
- [x] nodejs20
- [x] openblas
- [x] opencryptoki
- [x] opendnssec
- [x] openexr
- [x] openldap
- [x] openmpi
- [x] opensc: https://src.fedoraproject.org/rpms/opensc/pull-request/18
- [x] openscap
- [x] openssl-pkcs11: UNWANTED, work under way to remove
- [x] openwsman
- [x] p11-kit
- [x] perl-Bit-Vector
- [x] perl-DBD-MySQL
- [x] perl-Tk
- [x] perl-gettext
- [x] php
- [x] php-pecl-apcu
- [x] php-pecl-rrd: needs rrdtool i686 fix (rrdtool-1.8.0-16.fc40) to go stable
- [x] php-pecl-xdebug3
- [x] php-pecl-zip
- [x] pkcs11-helper
- [x] pkcs11-provider
- [x] pmix
- [x] postgresql16: https://src.fedoraproject.org/rpms/postgresql16/pull-request/2
- [x] procmail
- [x] python-dmidecode
- [x] python-iniparse
- [x] python-lxml
- [x] python-networkx
- [x] python-pygit2
- [x] python-pytest-mock
- [x] python-ruamel-yaml-clib
- [x] qt6-qttools
- [x] rapidjson
- [x] rrdtool
- [x] ruby
- [x] rust
- [x] sblim-sfcc
- [x] scipy
- [x] sdbus-cpp
- [x] softhsm
- [x] squid
- [x] star
- [x] strace
- [x] syslinux
- [x] tboot
- [x] tesseract
- [x] tix
- [x] unixODBC
- [x] volume_key
- [x] xdg-desktop-portal-gnome
- [x] xdp-tools
- [x] xorg-x11-server-Xwayland
- [x] zziplib

Mass rebuild is still in progress, will add more failures as they arise.

**Comment by yselkowitz** [comment]
Per today's meeting, also tracking this in https://lite.framacalc.org/tgyaghuoob-a5pt

**Comment by hroncok** [comment]
python-lxml was reported upstream as https://bugs.launchpad.net/lxml/+bug/2051243

**Comment by yselkowitz** [comment]
volume_key: https://src.fedoraproject.org/rpms/volume_key/pull-request/5

**Comment by yselkowitz** [comment]
xdp-tools: https://src.fedoraproject.org/rpms/xdp-tools/pull-request/1

**Comment by yselkowitz** [comment]
python-iniparse: https://src.fedoraproject.org/rpms/python-iniparse/pull-request/7

**Comment by yselkowitz** [comment]
python-pytest-mock: https://src.fedoraproject.org/rpms/python-pytest-mock/pull-request/7

**Comment by yselkowitz** [comment]
sdbus-cpp: https://src.fedoraproject.org/rpms/sdbus-cpp/pull-request/2

**Comment by yselkowitz** [comment]
ipxe: https://src.fedoraproject.org/rpms/ipxe/pull-request/6

(Thanks @michel-slm for finding the upstream fix.)

**Comment by yselkowitz** [comment]
kexec-tools: https://src.fedoraproject.org/rpms/kexec-tools/pull-request/20 by @michel-slm

**Comment by yselkowitz** [comment]
pkcs11-helper: https://src.fedoraproject.org/rpms/pkcs11-helper/pull-request/2

**Comment by yselkowitz** [comment]
syslinux: https://src.fedoraproject.org/rpms/syslinux/pull-request/5

**Comment by yselkowitz** [comment]
openexr: https://src.fedoraproject.org/rpms/openexr/pull-request/5

**Comment by yselkowitz** [comment]
libnxz: https://src.fedoraproject.org/rpms/libnxz/pull-request/8 courtesy of @tuliom

**Comment by yselkowitz** [comment]
dnf: https://src.fedoraproject.org/rpms/dnf/pull-request/23 courtesy of @kontura

**Comment by sgallagher** [comment]
libgit2: https://src.fedoraproject.org/rpms/libgit2/pull-request/6

**Comment by yselkowitz** [comment]
iproute: https://src.fedoraproject.org/rpms/iproute/pull-request/11 by @sgallagher

**Comment by yselkowitz** [comment]
libgphoto2: https://src.fedoraproject.org/rpms/libgphoto2/pull-request/5

**Comment by sgallagher** [comment]
fcoe-utils: https://src.fedoraproject.org/rpms/fcoe-utils/pull-request/6

**Comment by sgallagher** [comment]
openldap: https://src.fedoraproject.org/rpms/openldap/pull-request/11

**Comment by hroncok** [comment]
Decided to workaround python-lxml to be able to update to 5.1 in f40+ and c10s: https://src.fedoraproject.org/rpms/python-lxml/pull-request/39

**Comment by yselkowitz** [comment]
We have discovered that a number of packages were failing at the buildSRPMFromSCM step, which means that they didn't get far enough to register a build attempt, and therefore aren't showing up as failed builds.

- [ ] apr: https://src.fedoraproject.org/rpms/apr/pull-request/5
- [ ] lua-posix: rpmautospec issues with non-ascii characters in legacy changelog, being investigated
- [ ] php-pear: https://src.fedoraproject.org/rpms/php-pear/pull-request/1
- [ ] stalld: unresolved BR: bpftool

**Comment by yselkowitz** [comment]
brasero (workaround): https://src.fedoraproject.org/rpms/brasero/pull-request/3

**Comment by yselkowitz** [comment]
libfabric (workaround): https://src.fedoraproject.org/rpms/libfabric/pull-request/2

**Comment by yselkowitz** [comment]
libunwind: https://src.fedoraproject.org/rpms/libunwind/pull-request/8 by @kalev

**Comment by yselkowitz** [comment]
asio is waiting on a new gcc snapshot, which is now in testing.

**Comment by yselkowitz** [comment]
atlas will become a leaf via https://src.fedoraproject.org/rpms/flexiblas/pull-request/3

**Comment by yselkowitz** [comment]
gtk-doc still needs help: https://gitlab.gnome.org/GNOME/gtk-doc/-/issues/150

**Comment by yselkowitz** [comment]
openblas still needs help: https://github.com/OpenMathLib/OpenBLAS/issues/4475

**Comment by yselkowitz** [comment]
zziplib still needs help: https://bugzilla.redhat.com/show_bug.cgi?id=2256917

**Comment by yselkowitz** [comment]
perl-Tk still needs help: https://bugzilla.redhat.com/show_bug.cgi?id=2259172

**Comment by NeilHanlon** [comment]
gtk-doc: https://src.fedoraproject.org/rpms/gtk-doc/pull-request/2

**Comment by yselkowitz** [comment]
openblas: https://src.fedoraproject.org/rpms/openblas/pull-request/12 by @hhorak

**Comment by yselkowitz** [comment]
zziplib (workaround): https://src.fedoraproject.org/rpms/zziplib/pull-request/4

**Comment by yselkowitz** [comment]
atlas has been dropped, and perl-Tk has been fixed; that completes this list.
