### ISSUE TITLE
TASK: ELN tests in openQA failing since Fedora-ELN-20240120.1 with "failed to load driver: zink"

### ISSUE THREAD

**Issue by AdamWill** [fedora-eln/eln#177]
openQA tests of Fedora ELN have been failing since the Fedora-ELN-20240120.1 compose. openQA tests boot the 'dvd1' ISO in a qemu VM with virtio graphics and run a graphical install. Starting the graphical installer is failing with several errors relating to the 'zink' driver (which, IIRC, is part of Mesa's software OpenGL acceleration implementation - note the installer runs on top of gnome-kiosk, so it uses this stack). Here's a screenshot:

![screenshot of the error messages](https://github.com/fedora-eln/eln/assets/916551/4d5a50f4-70ef-4cc3-ad4b-f5c656841ef0)

The last working compose was Fedora-ELN-20240119.5.

**Comment by sgallagher** [comment]
Our composes have been failing in general for a few days; we just had a new one successfully a few minutes ago. Let's see how that goes.

**Comment by AdamWill** [comment]
If you mean Fedora-ELN-20240122.6, then [nope](https://openqa.fedoraproject.org/tests/overview?distri=fedora&version=ELN&build=Fedora-ELN-20240122.6&groupid=1).

**Comment by sgallagher** [comment]
Turns out the issue was due to Mesa having been built against a bad version of binutils. I just tested with a rebuild locally and it worked, so this should be fixed in the next compose.

**Comment by sgallagher** [comment]
The latest [OpenQA run](https://openqa.fedoraproject.org/tests/overview?distri=fedora&version=ELN&build=Fedora-ELN-20240125.5&groupid=1) has passed.

**Comment by AdamWill** [comment]
thanks for figuring it out! sorry I couldn't help, the piles of fire have been particularly burn-y this week.
