### ISSUE TITLE
TASK: Fix C10S FTBFS

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#179]
### What does the ELN SIG need to do?
* The following packages are building in rawhide and ELN -- and therefore packages tracked in #176 are excluded -- but are failing in CentOS Stream 10.  They need to be fixed for a successful conclusion to the bootstrap.

- [x] alsa-sof-firmware: ALSA dependencies were built out of order, need rebuilding
- [x] clang: i686 OOM, https://src.fedoraproject.org/rpms/clang/pull-request/227
- [x] dotnet8.0: runtime_id does not match fedora/eln, may need to be bootstrapped
- [x] gmp - https://issues.redhat.com/browse/RHEL-24891
- [x] grub2: `error: cannot open %{sb_cer}`
- [x] iproute: `rt_dsfield.deprecated` needs to be imported post-branching
- [x] ksh
- [x] libecpg - https://issues.redhat.com/browse/RHEL-24889
- [x] libkcapi
- [x] liblouis
- [x] nettle
- [x] perl-DBD-MySQL: waiting for a real mysql package (being renamed from community-mysql)
- [ ] pkcs11-provider
- [x] pygobject3
- [x] python-psutil - https://issues.redhat.com/browse/RHEL-24890
- [x] python-pygit2: 
- [x] python3.12: needs bootstrapping without ELN builds in inheritance
- [x] ruby - tests trying to access outside network - https://issues.redhat.com/browse/RHEL-25008
- [x] rubygem-eventmachine
- [x] scap-security-guide: no upstream EL10 content; should be treated as a placeholder
- [x] scipy
- [x] snowball
- [x] tftp
- [x] tracker-miners: `meson.build:208:4: ERROR: Problem encountered: Landlock was enabled in build options, but is disabled in the kernel`
- [x] varnish: test flakes, retry

**Comment by hroncok** [comment]
Feel free to ping me for python3.12 bootstrap.

**Comment by yselkowitz** [comment]
@tdawson once `alsa-utils-1.2.11-1.eln135` has synced over to the c10s buildroot, please retry alsa-sof-firmware

**Comment by yselkowitz** [comment]
tracker-miners: https://gitlab.gnome.org/GNOME/tracker-miners/-/issues/300

**Comment by yselkowitz** [comment]
rubygem-eventmachine: DROP via https://src.fedoraproject.org/rpms/rubygem-mysql2/pull-request/17

**Comment by yselkowitz** [comment]
tftp appears to be a race condition in the Makefile, but I can't reproduce locally.  Serializing the build should work around it.

**Comment by yselkowitz** [comment]
libecpg also appears to be a race condition in the Makefiles.

**Comment by tdawson** [comment]
ruby is trying to access the outside network during it's tests - https://issues.redhat.com/browse/RHEL-25008

**Comment by yselkowitz** [comment]
> ruby is trying to access the outside network during it's tests - https://issues.redhat.com/browse/RHEL-25008

This sounds like a koji/mock configuration difference between Fedora/ELN and CS/RHEL, because the same tests don't fail in the former?

**Comment by tdawson** [comment]
> > ruby is trying to access the outside network during it's tests - https://issues.redhat.com/browse/RHEL-25008
> 
> This sounds like a koji/mock configuration difference between Fedora/ELN and CS/RHEL, because the same tests don't fail in the former?

I believe you are correct.  This was happening with some other package as well.  I'm not remembering which.
I personally do not like tests that try to access the outside network unless they can be turned off in a real way.  The ones that look and see if your network has such and such a configuration are simply too fragile.

**Comment by yselkowitz** [comment]
tracker-miners: https://src.fedoraproject.org/rpms/tracker-miners/pull-request/8

**Comment by yselkowitz** [comment]
liblouis: https://src.fedoraproject.org/rpms/liblouis/c/bac0acc0b1517ca1ed08281fee7c3542d482def4?branch=rawhide (mistakenly did fedpkg push instead of fedpkg fork, although given the time constraints I probably would have had to merge the PR myself anyway...)

**Comment by yselkowitz** [comment]
tftp: https://src.fedoraproject.org/rpms/tftp/pull-request/4

**Comment by yselkowitz** [comment]
snowball: https://src.fedoraproject.org/rpms/snowball/pull-request/2

**Comment by yselkowitz** [comment]
python-pygit2: https://src.fedoraproject.org/rpms/python-pygit2/pull-request/3

**Comment by yselkowitz** [comment]
pygobject3: https://src.fedoraproject.org/rpms/pygobject3/pull-request/6

**Comment by yselkowitz** [comment]
liblouis part 2: https://src.fedoraproject.org/rpms/liblouis/pull-request/6

**Comment by yselkowitz** [comment]
pkcs11-provider test failure is related to softhsm.  There have been a number of issues with tests using softhsm due to internal changes in the crypto stack.  Disabling the `BuildRequires: softhsm` is a workaround, at least for the purposes of bootstrapping (there has yet to be a build in c10s).

**Comment by tdawson** [comment]
ruby: https://src.fedoraproject.org/rpms/ruby/pull-request/170

**Comment by yselkowitz** [comment]
Bootstrap is complete; remaining issues are now up to the maintainers to solve.
