### ISSUE TITLE
TASK: ELN cannot boot with Secure Boot enabled

### ISSUE THREAD

**Issue by AdamWill** [fedora-eln/eln#183]
### What does the ELN SIG need to do?
* Fix Fedora ELN to boot with Secure Boot enabled. It does not work because ELN's grub2 package (and possibly others) is not correctly signed, per @sgallagher , and we may need someone with the appropriate privileges to rebuild it.

**Comment by sgallagher** [comment]
Options I see:
 
 1. Have someone trusted do the ELN builds
 2. Give that privilege to the sync tool bot so it can just do the rebuilds
 3. Just tag the Rawhide build in

I don't like 3. because it means we can't be sure if it works if built like RHEL

**Comment by yselkowitz** [comment]
@sgallagher weren't the `package.cfg` files going to fix this?  At least grub2 still isn't being built for ELN.

**Comment by sgallagher** [comment]
It hasn't been built since the fedpkg release that added that support.

**Comment by sgallagher** [comment]
https://koji.fedoraproject.org/koji/buildinfo?buildID=2519158 finally exists and is in the latest compose.

**Comment by yselkowitz** [comment]
@AdamWill is anything further needed here?

**Comment by AdamWill** [comment]
Oh, cool, I missed that this was expected to be fixed now. I don't know if it works yet, as I flipped the ELN tests to running on BIOS to avoid this. I'll flip them back to UEFI+SB and see if it works.

**Comment by AdamWill** [comment]
Yup, looks like this works:
```
Script:
mokutil --sb-state

Check function (deparsed code):
{
    package uefi_postinstall;
    /SecureBoot enabled/;
}

Output:
SecureBoot enabled
```
Thanks!
