### ISSUE TITLE
TASK: Fix font in ELN installer image

### ISSUE THREAD

**Issue by AdamWill** [fedora-eln/eln#184]
### What does the ELN SIG need to do?
* Fix the font in the installer image. Between Fedora-ELN-20240425.4 (good) and Fedora-ELN-20240425.5 (bad), it changed from being the same font used in regular Fedora installer images (which I think is Cantarell) to...something else, I'm not sure what. Before:

![elnbefore](https://github.com/fedora-eln/eln/assets/916551/03eb2363-4998-41e3-b1ee-15ccd808a537)

After:

![elnafter](https://github.com/fedora-eln/eln/assets/916551/928b29df-bd1f-4210-a42b-11495e6097d9)

This breaks the openQA tests. I'm not inclined to fix them to deal with the new font as it would require maintaining a substantial amount of needles in parallel to the ones used by every other test flow.

**Comment by yselkowitz** [comment]
I think https://src.fedoraproject.org/rpms/langpacks/c/6dee1d16980e5ebb1cfbedeedb46f5978b6d2cba?branch=rawhide might be the cause of this.

**Comment by AdamWill** [comment]
apparently this is intentional :(

I've gone ahead and re-done the needles in openQA for now. but to call out clearly the consequences of this cosmetic change for testing:

* I had to spend an hour re-doing the needles
* Any time anything ever changes an affected needle again - anaconda changing the text, GTK or some other part of the stack changing rendering - our work to adapt to it is doubled because we now have to redo two needles
* It makes it much harder to extend the set of openQA tests we run on ELN, because it's much more likely I would need to add yet more variant needles to do so
