### ISSUE TITLE
TASK: Move python3-pytest from AppStream to CRB

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#185]
### What does the ELN SIG need to do?

https://tiny.distro.builders/view-rpm--view-eln--python3-pytest.html is listed in AppStream.

It is not required nor desired in AppStyream. It belongs to CRB.

https://pagure.io/pungi-fedora/blob/eln/f/prepopulate.json has it in CRB.

Please move it, or tell me how to move it myself. Thanks.

**Comment by sgallagher** [comment]
It can be moved by modifying its entry in https://pagure.io/pungi-fedora/blob/eln/f/prepopulate.json

I can look into it later this week, but if you want to submit a merge request before that, I'll happily review and merge it.

**Comment by hroncok** [comment]
As said in the ticket, I belive https://pagure.io/pungi-fedora/blob/eln/f/prepopulate.json has it in CRB.

**Comment by hroncok** [comment]
```pycon
>>> import json
... for repo in (prepopulate := json.load(open("prepopulate.json"))):
...     for arch in prepopulate[repo]:
...         for pkg in ("pytest",):
...             if pkg in prepopulate[repo][arch]:
...                 print(repo, arch, prepopulate[repo][arch][pkg])
... 
CRB aarch64 ['python3-pytest.noarch']
CRB ppc64le ['python3-pytest.noarch']
CRB s390x ['python3-pytest.noarch']
CRB x86_64 ['python3-pytest.noarch']
```

**Comment by sgallagher** [comment]
Sorry, I misread. OK, something strange is going on here... Everything I can see suggests it should be ending up in CRB, but it isn't. I'll dig further.

**Comment by hroncok** [comment]
I suspect https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/AppStream/x86_64/os/Packages/fabtests-1.18.0-6.eln136.x86_64.rpm is pulling it into AppStream.

It is not visible in the content resolver but is somehow still part of the compose.

The change that should have removed it: https://github.com/minimization/content-resolver-input/pull/1143

**Comment by hroncok** [comment]
Now when https://github.com/minimization/content-resolver-input/pull/1164 was merged, this is no longer relevant until I reopen it.
