### ISSUE TITLE
TASK: Adjustments for ghc-srpm-macros removal

### ISSUE THREAD

**Issue by fweimer-rh** [fedora-eln/eln#186]
The `ghc-srpm-macros` package is no longer installed as part of the SRPM buildroot, so more GHC-related packages will fail to build. This shouldn't be a problem because GHC (under any of its package names) is not expected to be part of ELN, but there have been attempts to build it in the past.

**Comment by yselkowitz** [comment]
Ack, a possible issue wrt ELN Extras packages has already been raised in #187 and will be addressed there.  In ELN proper though, ghc is not wanted and has already been removed for some time.
