### ISSUE TITLE
TASK: Disable i686 architecture in ELN

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#188]
### What does the ELN SIG need to do?
c10s disabled i686, so I suppose this is the case for c11s as well. Should Fedora ELN disable i686 builds?

**Comment by yselkowitz** [comment]
Yes, we're doing just that.  Steps:

- [ ] Content Resolver cleanup: https://github.com/minimization/content-resolver-input/pull/1192
- [ ] Modify eln-build tag in koji (releng ticket)

Anything else?

**Comment by hroncok** [comment]
Don't know about anything else, opened this mostly for the Koji tag thing.

**Comment by yselkowitz** [comment]
There is currently an ELN mass rebuild in progress to clean up after Perl 5.40 and Python 3.13; I don't want to change things until that completes.

**Comment by sgallagher** [comment]
Yeah, I wish we had gotten the notice about the i686 thing before I kicked that off, but oh well. The mass-rebuild is now  (mostly) complete. All the packages that succeeded have been tagged into -candidate and are slowly processing through the signing queue. It should be safe to start applying these changes now.

**Comment by yselkowitz** [comment]
https://pagure.io/releng/issue/12171

**Comment by yselkowitz** [comment]
This seems to be done.

**Comment by hroncok** [comment]
Thank you.

**Comment by yselkowitz** [comment]
Just discovered that Fedora COPR still offers a fedora-eln-i386 buildroot, as does mock.  Filed https://github.com/rpm-software-management/mock/pull/1413; is something else needed for COPR?

**Comment by hroncok** [comment]
I belive it is, but the copr people are the mock people, so they will know.

**Comment by yselkowitz** [comment]
Also filed https://github.com/fedora-copr/copr/issues/3339

**Comment by yselkowitz** [comment]
ix86 will be removed in the next mock-core-configs release, and has been EOL'd in copr.
