### ISSUE TITLE
TASK: Move pyproject-rpm-macros to CRB

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#190]
### What does the ELN SIG need to do?

[pyproject-rpm-macros](https://tiny.distro.builders/view-rpm--view-eln--pyproject-rpm-macros.html) is listed in ELN AppStream. It belongs in ELN CRB.

AFAIK nothing pulls pyproject-rpm-macros into AppStream. Other packages only BuildRequire it or conditionally Require it.

There is this runtime dependency in [pyproject-srpm-macros](https://tiny.distro.builders/view-rpm--view-eln--pyproject-srpm-macros.html) (in AppStream):

```
(pyproject-rpm-macros = 1.12.2-1.eln140 if pyproject-rpm-macros)
```

Such dependency should not pull pyproject-rpm-macros into AppStream.

The package is listed in the CRB repos in [prepopulate.json](https://pagure.io/pungi-fedora/blob/eln/f/prepopulate.json).

This works correctly in c9s, but seems to misbehave in ELN and [c10s](https://issues.redhat.com/browse/ENGCMP-4166).

Thanks

**Comment by sgallagher** [comment]
Sorry for the delay. I'm looking into this now.

**Comment by hroncok** [comment]
https://gitlab.com/redhat/centos-stream/release-engineering/pungi-centos/-/merge_requests/705 fixed this in c10s

**Comment by sgallagher** [comment]
Fixed now, sorry for the delay.

**Comment by hroncok** [comment]
Thanks. Linking https://pagure.io/pungi-fedora/c/c23b4edb2e5e99588bb1af46389b72ea9f7f15f1?branch=eln for reference
