### ISSUE TITLE
TASK: Fix F41 FTBFS from ELN package set

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#191]
### What does the ELN SIG need to do?
* The F41 mass rebuild is going to have a number of FTBFS.  These need to be fixed before an ELN build will be triggered.

List of all F41FTBFS (although our focus is only on the ELN package set): https://kojipkgs.fedoraproject.org/mass-rebuild/f41-failures.html

- [x] Cython
- [x] alsa-sof-firmware
- [x] apr-util: openssl-devel-engine
- [x] asio: openssl-devel-engine?
- [x] awscli2: SHA1 in tests
- [x] colord: docbook5-style-xsl breakage
- [x] colord-gtk: docbook5-style-xsl breakage
- [x] delve: version mismatch with golang
- [x] galera: openssl-devel-engine
- [x] gcc: docbook5-style-xsl breakage
- [x] git: docbook5-style-xsl breakage
- [x] glib2: flaky test?
- [x] iputils: docbook5-style-xsl breakage
- [ ] jss
- [x] kea: asio+openssl-devel-engine
- [x] ksh: flaky test?
- [x] ldns: openssl-devel-engine
- [x] libblockdev: e2fsprogs API break
- [x] libguestfs: flaky test?
- [x] libkcapi
- [x] libnotify: docbook5-style-xsl
- [x] libnvme: openssl-devel-engine
- [x] libpq: openssl-devel-engine
- [x] libproxy: flaky tests?
- [ ] librelp: openssl-devel-engine
- [x] libssh: openssl-devel-engine
- [x] libtpms: openssl-devel-engine
- [x] libvirt: flaky tests?
- [x] libvirt-python: libvirt version mismatch
- [x] libvma: https://github.com/Mellanox/libvma/pull/1076 and https://src.fedoraproject.org/rpms/libvma/pull-request/3
- [ ] mariadb10.11: fmt v11 incompatibility
- [x] msitools: mingw-icu version mismatch
- [ ] mstflint: openssl-devel-engine
- [x] nbdkit
- [x] net-snmp: flaky tests?
- [x] openpace
- [x] openssl-pkcs11 (UNWANTED): openssl-devel-engine
- [x] pam: docbook5-style-xsl
- [x] php-pecl-apcu
- [x] php-pecl-zip
- [x] pkcs11-provider: flaky tests?
- [x] ptyxis: premature version bump needs pre-release vte291
- [x] pytest
- [x] python-lxml
- [x] qatengine: openssl-devel-engine
- [ ] rsyslog: openssl-devel-engine
- [x] rubygem-pg
- [x] rust-sevctl: rust-sev updated to v3, sevctl still needs v1; either create rust-sev1 compat package or update sevctl to git snapshot
- [x] s-nail
- [x] scipy: pybind11 version mismatch
- [ ] softhsm: openssl-devel-engine
- [ ] tboot: openssl-devel-engine
- [x] torque
- [ ] tpm2-openssl
- [x] tpm2-tss: openssl-devel-engine
- [ ] tss2: openssl-devel-engine
- [x] udisks2: libstoragemgmt is now disabled on ix86
- [ ] unbound: flaky test?
- [x] valkey
- [x] varnish: flaky tests?
- [x] virt-v2v: flaky test?
- [x] wpa_supplicant: openssl-devel-engine

**Comment by jonathanspw** [comment]
valkey is caused by a flakey test on ppc64le it seems.  I'm not sure why though, as these tests works fine in Fedora/EPEL koji, local mockbuilds, and COPR.

**Comment by hroncok** [comment]
Cython is https://bugzilla.redhat.com/show_bug.cgi?id=2293086 == https://github.com/cython/cython/issues/6251

**Comment by hroncok** [comment]
pytest is https://bugzilla.redhat.com/show_bug.cgi?id=2275051 -- this is fixed by pytest 8 via https://fedoraproject.org/wiki/Changes/Pytest_8 (still not delivered, but just about to)

**Comment by jonathanspw** [comment]
valkey scratch-build worked.  It's a flaky test.

https://koji.fedoraproject.org/koji/taskinfo?taskID=120857479

Re-triggered rawhide build.

**Comment by jonathanspw** [comment]
Did a rebuild of valkey and the tests passed.

https://koji.fedoraproject.org/koji/taskinfo?taskID=120857682

**Comment by yselkowitz** [comment]
Proposed fix for docbook5-style-xsl: https://src.fedoraproject.org/rpms/docbook5-style-xsl/pull-request/2

**Comment by yselkowitz** [comment]
udisks2: https://src.fedoraproject.org/rpms/udisks2/pull-request/6

**Comment by yselkowitz** [comment]
msitools: https://src.fedoraproject.org/rpms/msitools/pull-request/6

**Comment by yselkowitz** [comment]
openpace: https://src.fedoraproject.org/rpms/openpace/pull-request/1

**Comment by yselkowitz** [comment]
libvirt-python: https://src.fedoraproject.org/rpms/libvirt-python/pull-request/4

**Comment by yselkowitz** [comment]
awscli2: https://src.fedoraproject.org/rpms/awscli2/pull-request/142

**Comment by yselkowitz** [comment]
Folding this into #198
