### ISSUE TITLE
TASK: Fix ELN Extras rebuild

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#193]
### What does the ELN SIG need to do?
The rebootstrapping of ELN Extras is nearly complete

- [x] armadillo:  https://src.fedoraproject.org/rpms/armadillo/pull-request/2
- [x] cantor:  needs poppler-qt5
- [ ] clamav
- [x] digikam:  https://src.fedoraproject.org/rpms/digikam/pull-request/5
- [x] dvdauthor:  https://src.fedoraproject.org/rpms/ImageMagick/pull-request/12
- [ ] fsverity-utils:  openssl-devel-engine
- [x] ghostwriter:  missing `%qt5_qtwebengine_arches` macro (note: moving to Qt6 with 24.08.0)
- [x] grpc:  openssl-devel-engine
- [x] haruna:  pipewire-jack symbols not found
- [x] kig:  https://src.fedoraproject.org/rpms/kig/pull-request/4
- [x] kreport:  https://src.fedoraproject.org/rpms/kreport/pull-request/5
- [x] marble:  https://src.fedoraproject.org/rpms/marble/pull-request/2
- [x] netcdf
- [x] nvml:  https://src.fedoraproject.org/rpms/nvml/pull-request/8
- [x] openbabel:  https://src.fedoraproject.org/rpms/openbabel/pull-request/5
- [ ] openconnect
- [ ] openfortivpn:  openssl-devel-engine
- [x] pcs:  https://src.fedoraproject.org/rpms/resource-agents/pull-request/9
- [x] python-TestSlide:  https://src.fedoraproject.org/rpms/python-TestSlide/pull-request/4
- [x] python-b4:  https://src.fedoraproject.org/rpms/python-b4/pull-request/8
- [x] python-bcrypt:  https://src.fedoraproject.org/rpms/python-setuptools-rust/pull-request/10
- [ ] python-django:  needs `python3-urllib3+socks` (extras not included in RHEL package)
- [x] qt5-qtwebengine:  missing `%qt5_qtwebengine_arches` macro
- [x] qt6-qtwebengine:  aarch64 syscalls issue
- [x] ragel:  docs require `pdflscape.sty`
- [ ] rubygem-puma
- [ ] strongswan:  openssl-devel-engine
- [x] tokodon:  pipewire-jack symbols not found
- [x] unity-gtk-module:  https://src.fedoraproject.org/rpms/unity-gtk-module/pull-request/3

**Comment by hroncok** [comment]
We will not include `python3-urllib3+socks` in RHEL. If this is needed in EPEL, it needs to be packaged separately. See e.g. https://src.fedoraproject.org/rpms/python-jsonschema-epel/blob/epel9/f/python-jsonschema-epel.spec

**Comment by yselkowitz** [comment]
"pipewire-jack symbols not found" reported: https://issues.redhat.com/browse/RHEL-53183

**Comment by tdawson** [comment]
qt5-qtwebengine will not be in epel11.  Rather than waste cycles trying to get it to build in eln-extras, I'd rather remove the packages pulling it in.  Or, if possible, fix the spec files so they don't do qt5 stuff.
https://tiny.distro.builders/view-rpm--view-eln-extras--qt5-qtwebengine.html

**Comment by yselkowitz** [comment]
> qt5-qtwebengine will not be in epel11. Rather than waste cycles trying to get it to build in eln-extras, I'd rather remove the packages pulling it in. 

Delist cantor and kaidan: https://github.com/minimization/content-resolver-input/pull/1255
Disable usage in marble: https://src.fedoraproject.org/rpms/marble/pull-request/2

Also, I'm guessing we don't want Qt5WebKit in EPEL 10 either, since we're trying to drop that altogether.  To that end:

Disable usage in kexi: https://src.fedoraproject.org/rpms/kexi/pull-request/3
Disable usage in kreport: https://src.fedoraproject.org/rpms/kreport/pull-request/5

That leaves ghostwriter and kdevelop, which will move to Qt6 (and hence Qt6WebEngine) in 24.08 (the 24.07.90 RC should be out any day now).

**Comment by yselkowitz** [comment]
missing texlive-pdflscape dependency reported: https://issues.redhat.com/browse/RHEL-53786 (MR to follow)

**Comment by yselkowitz** [comment]
We really want to avoid -epel packages for ELN Extras due to the maintenance burden, so filed: https://src.fedoraproject.org/rpms/python-urllib3/pull-request/38

**Comment by yselkowitz** [comment]
Consolidating into #198
