### ISSUE TITLE
TASK: resolve version inconsistency between ELN composes and updates ("eln" versus "ELN")

### ISSUE THREAD

**Issue by AdamWill** [fedora-eln/eln#199]
### What does the ELN SIG need to do?
* Fix a version inconsistency between ELN composes and releases.

The compose metadata for ELN composes gives the version as "ELN", upper-case. See e.g. https://kojipkgs.fedoraproject.org/compose/eln/Fedora-ELN-20240903.n.1/compose/metadata/composeinfo.json (and it's the same for ODCS composes). But the metadata for ELN updates in Bodhi gives the version as "eln", lower-case. See the JSON representation of any ELN update in Bodhi - e.g. do `http get https://bodhi.fedoraproject.org/updates/FEDORA-2024-63fc9d528e`. The "version" in the "release" dict is "eln".

If I hadn't spotted this it would've led to the VERSION value for openQA ELN update tests being different from the one for openQA ELN compose tests, which would've been weird and irritating. It might lead to similar weird inconsistencies for other tools if they try and do stuff with both ELN composes and updates.

**Comment by AdamWill** [comment]
@sgallagher says he thinks it should always be lower-case, in which case https://pagure.io/pungi-fedora/blob/eln/f/fedora/variables.conf#_6 should change.

**Comment by sgallagher** [comment]
For the record, I'm going to invent official branding rules here and now:

* Any location where it is expected to be presented to a human reader should use the upper-case form: ELN. This is to indicate that it is both a proper name and an initialization.
* Any location where it is intended to be parsed only by computer, it should be lowercase (which is easier to normalize for a case-insensitive comparison).

I'll get these rules added to our SIG docs so we don't forget later.

**Comment by AdamWill** [comment]
I think this is done now, right?
