### ISSUE TITLE
TASK: Remove ResilientStorage variant

### ISSUE THREAD

**Issue by yselkowitz** [fedora-eln/eln#205]
### What does the ELN SIG need to do?
The ResilientStorage (RS) variant has been dropped from c10s composes; ELN should follow suit.

- [x] Content Resolver input: https://github.com/minimization/content-resolver-input/pull/1300
- [x] Content Resolver test configs
- [x] pungi-configs: included in https://pagure.io/pungi-fedora/pull-request/1393
- [x] fedora-comps
- [x] fedora-repos
- [x] mock-core-configs
- [x] Content on dl.fp.o
- [x] mirrormanager configuration
- [ ] what else?

**Comment by sgallagher** [comment]
fedora-comps: https://pagure.io/fedora-comps/pull-request/1040

**Comment by sgallagher** [comment]
fedora-repos: https://src.fedoraproject.org/rpms/fedora-repos/pull-request/150

**Comment by yselkowitz** [comment]
https://github.com/minimization/content-resolver/pull/70

**Comment by yselkowitz** [comment]
https://github.com/rpm-software-management/mock/pull/1492

**Comment by yselkowitz** [comment]
mirrors: https://github.com/fedora-infra/mirrormanager2/issues/409

**Comment by yselkowitz** [comment]
https://pagure.io/releng/issue/12459

**Comment by yselkowitz** [comment]
@sgallagher is there anything further to be done here?

**Comment by sgallagher** [comment]
Not so far as I am aware.
