### ISSUE TITLE
bash package missing from the repository

### ISSUE THREAD

**Issue by juanje** [fedora-eln/eln#21]
Today we (at [CKI project](https://cki-project.org/)) realized that the package `bash` was missing from the Fedora ELN repository.
`dnf` tries to download the package but it fails:
https://gitlab.com/cki-project/containers/-/jobs/912182861#L963

```
[MIRROR] bash-5.0.17-3.eln107.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/Packages/bash-5.0.17-3.eln107.x86_64.rpm (IP: 38.145.60.20)
[MIRROR] bash-5.0.17-3.eln107.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/Packages/bash-5.0.17-3.eln107.x86_64.rpm (IP: 38.145.60.20)
[MIRROR] bash-5.0.17-3.eln107.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/Packages/bash-5.0.17-3.eln107.x86_64.rpm (IP: 38.145.60.20)
[MIRROR] bash-5.0.17-3.eln107.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/Packages/bash-5.0.17-3.eln107.x86_64.rpm (IP: 38.145.60.20)
[FAILED] bash-5.0.17-3.eln107.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
```

I checked the link and the browser show me this message:
```
Forbidden

You don't have permission to access this resource.
```

If you go to the directory (https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/Packages/) it's working fine and the rest of packages are there, but there is no `bash` package.

If I check the files at https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/repodata/ I can see the package listed (that's why `dnf` find the package URL and tried to download it).

So it seems that the package is still listed as part of that compose, but somehow the package itself has been removed.

**Comment by contyk** [comment]
We had some issues with composes for the last week. I see the package is there now.
Does this resolve your problem?

**Comment by contyk** [comment]
But also ping @hanzz -- how could that happen?

**Comment by juanje** [comment]
@contyk Thanks! I see the package now. I'll check if now it builds.

**Comment by juanje** [comment]
@contyk Yes, it looks like it's working again:

https://gitlab.com/cki-project/containers/-/jobs/915516537

Thanks!
