### ISSUE TITLE
Collect topics for Fedora ELN Meetup at the Devconf.cz 2021

### ISSUE THREAD

**Issue by bookwar** [fedora-eln/eln#26]
On Saturday, February 20, 2021 we are going to have Fedora ELN Meetup at the Devconf.cz

https://devconfcz2021.sched.com/event/gmYF/fedora-eln-meetup

Let's use this issue for topics and discussion items which we want to cover at the meetup.

Anyone can suggest the item via a comment.

**Comment by contyk** [comment]
I think I'd have two potential topics.

1. Long term goals of ELN. Clearly ELN serves as a base for the next major version of RHEL but is there any interest to keep it alive, installable and in generally good shape during the long, quiet periods between releases (effectively around two years)? Are RHEL SSTs going to be maintaining their workloads? How much effort should we invest in more automation to keep it ticking? Consider how much babysitting it requires right now. If there's general interest, should ELN become more visible to general Fedora maintainers?

2. Current technical issues regarding proper build ordering, with and without side tag merges. Painless mass rebuilds without pipeline crashes. Handling component renames and other outstanding challenges.

**Comment by bookwar** [comment]
Etherpad for real-time coordination

https://etherpad.gnome.org/p/fedora-eln-meetup

**Comment by bookwar** [comment]
@sgallagher FYI

**Comment by bookwar** [comment]
# Topics

## What is ELN

Alternative buildroot for Fedora Rawhide

https://raw.githubusercontent.com/fedora-eln/eln-docs/2b865992b452ea4a1a4a93d3a7a791ba57002dd3/modules/ROOT/assets/images/fedora-eln-centos-stream-rhel.png 

## Current status

* https://docs.fedoraproject.org/en-US/eln/status

SAME  3638  97.80%   Rawhide and ELN builds are caught up
OLD   76    2.04%    ELN build is older than Rawhides
NONE  6     0.16%    There is no ELN build
TOTAL 3720  100.00%  Total ELN packages

~50 FTBFS bugs were filed for Red Hat Developers
RHEL 9 has been bootstrapped from ELN and since last week ELN is looking to RHEL 10

* Components:
* Content Resolver - calculate dependency trees for sets of workloads
https://tiny.distro.builders/view--view-eln.html 
* Automation to rebuild every package from Fedora Rawhide which is listed in the content set
* ELN Compose including container images
* Comparison of Koji/Brew tags

* ELN SIG Launch
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/7W5LONBAPURDWPCCIQUS25IKYLKUI2CX/#XID5FJRRGKT4PEF2CG2B3LI6K32DEQPG


## Long term goals of ELN

Clearly ELN serves as a base for the next major version of RHEL but is there any interest to keep it alive, installable and in generally good shape during the long, quiet periods between releases (effectively around two years)? Are RHEL SSTs going to be maintaining their workloads? How much effort should we invest in more automation to keep it ticking? Consider how much babysitting it requires right now. If there's general interest, should ELN become more visible to general Fedora maintainers?

## Current technical issues

* Build ordering, with and without side tag merges
* Painless mass rebuilds without pipeline crashes
* Handling component renames
* Handling notifications
* Other outstanding challenges

## Other topics

* Fedora ELN CI jobs at Pull Requests?
* Communication channels? [ELN] on devel list doesn't work
* ELN Fedora container images
    * https://docs.fedoraproject.org/en-US/eln/deliverables/
    
# Notes
Reuse %check decoupled from the koji build:
with mock (needed for %genearate_buildrequires):
https://src.fedoraproject.org/rpms/python-tox/blob/e2c1378f4/f/tests/tests.yml#_29
with rpmbuild:
https://src.fedoraproject.org/rpms/python-tox/blob/d26876d9d/f/tests/tests.yml#_29


# Action items

* Create pipeline to build ELN on pull request and test with dist-git test
-> https://github.com/fedora-eln/eln/issues/30
