### ISSUE TITLE
fedora-release should define rhel as 10

### ISSUE THREAD

**Issue by fweimer-rh** [fedora-eln/eln#29]
`fedora-release-common-35-0.2.eln110.noarch` is still set up as major release 9, as far as I can see.

**Comment by fweimer-rh** [comment]
This issue is based on

> ELN is a new buildroot and compose process for Fedora that takes Fedora Rawhide dist-git sources and emulate a Red Hat Enterprise Linux compose. [(source)](https://docs.fedoraproject.org/en-US/eln/)

If ELN is not actually tracking rawhide, then bumping the major release number at this point would be premature.

**Comment by sgallagher** [comment]
That's a bug, but it shouldn't actually be affecting the builds because we override that value in the `eln-build` tag:

```
$ koji taginfo eln-build
Tag: eln-build [22493]
Arches: i686 x86_64 aarch64 ppc64le s390x
Groups: appliance-build, build, livecd-build, livemedia-build, srpm-build
Tag options:
  mock.new_chroot : 0          [f35]
  mock.package_manager : 'dnf' [f35]
  rpm.macro.dist : ('%{!?distprefix0:%{?distprefix}}%{expand:%{lua:for i=0,9999 do '
 'print("%{?distprefix" .. i .."}") '
 'end}}.eln%{eln}%{?with_bootstrap:~bootstrap}')
  rpm.macro.eln : 110
  rpm.macro.rhel : 10
This tag is a buildroot for one or more targets
Current repo: repo#3027769: 2021-02-20 09:25:57.696592+00:00
Targets that build from this tag:
  eln-rebuild
  eln
  eln-candidate
Inheritance:
  0    .... eln [22492]
```

But yeah, the fedora-release value should indeed be updated to match.

**Comment by sgallagher** [comment]
https://src.fedoraproject.org/rpms/fedora-release/pull-request/170

**Comment by hroncok** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2021-5bf61befbf
