### ISSUE TITLE
Disable armv7hl builds

### ISSUE THREAD

**Issue by jwboyer** [fedora-eln/eln#3]
At the time of ELN's creation, the premise was to build ELN for all architectures that Fedora supports.  This has largely continued, however there are notable exceptions on the armv7hl architecture.  Specifically, the kernel itself is not built leading to what largely amounts to a non-functional compose for that architecture.

Additionally, there is not a well-define set of requirements for what Enterprise focused development would need for this architecture.  This causes individual packages to base the feature set on what is available for other architectures by default, or vary based on individual guesses.  The burden for some maintainers is significant.

Please disable the armv7hl architecture for ELN.  This will help focus ELN on the requirements for Enterprise and alleviate burden on machine and maintainer resources within the Fedora community.

**Comment by jwboyer** [comment]
@sgallagher @tdawson I think this is complete now?

**Comment by sgallagher** [comment]
Yes, confirmed this morning that we are no longer building or producing composes for armv7hl in ELN.
