### ISSUE TITLE
Document checklist for branching

### ISSUE THREAD

**Issue by bookwar** [fedora-eln/eln#32]
We have two branching events on the infrastructure: Fedora Rawhide branching every 6 months and RHEL branching approximately every 3 years. Both events have a list of associated actions. So we need to track them.

@tdawson You have a list of thing already, I believe, but these are additional items:

* [Fedora Branching] Trigger for ELN pipeline https://github.com/fedora-ci/eln-build-trigger/pull/2

* [RHEL Branching] el-release https://github.com/fedora-eln/eln/issues/29

**Comment by bookwar** [comment]
I would just say "branching" and put it under Infrastructure section

**Comment by tdawson** [comment]
Pull request is in.
It has the basic layout, Fedora Branching, RHEL Branching.
Fedora branching has an entry for "Trigger for ELN Pipeline", as well as my "ELN fedora release and repo"
It didn't put anything under the RHEL Branching other than the basic description.

https://github.com/fedora-eln/eln-docs/pull/19

**Comment by tdawson** [comment]
The document is there now
https://docs.fedoraproject.org/en-US/eln/branching/

My stuff is on it.  If others want to update it, it is here
https://github.com/fedora-eln/eln-docs/blob/master/modules/ROOT/pages/branching.adoc
