### ISSUE TITLE
SIG Members: Make your org membership public

### ISSUE THREAD

**Issue by sgallagher** [fedora-eln/eln#37]
I'd like to use the membership in our Github Organization the official record of who is an active member of the SIG. However, in order to do this, we all need to make our membership a matter of public record. Please browse to https://github.com/orgs/fedora-eln/<github_name>, and select `public` from the `membership` drop-down on the left.

**Comment by michel-slm** [comment]
@sgallagher a couple of things
- I think the right URL is https://github.com/orgs/fedora-eln/<github_name>
- my invitation expired, could I get re-invited?

**Comment by sgallagher** [comment]
You are a full member
