### ISSUE TITLE
New ELN-based workload for 'extra' packages

### ISSUE THREAD

**Issue by michel-slm** [fedora-eln/eln#45]
Per @bookwar, to have something like "EPEL for ELN" or "ELN Extras" we would need a separate workload defined in
https://github.com/minimization/content-resolver

and a starting set of packages we want to build. Dependencies will be resolved and pulled in automatically, so for those who want to use this to prep for the next wave of EPEL branch requests, the added bonus is we only have to list the actual packages we care about.

**Comment by tdawson** [comment]
I talked with Adam about this.  This will require creating a new label and view for Content Resolver.  The view would use the two labels eln and eln-extras.  The new workload(s) would then use the label eln-extras.  This would generate a new view with new lists of packages that should include both ELN and ELN-Extras.
The build scripts would then have to take a diff before the ELN view and the ELN-Extras view, and build all the extras in the ELN-Extras target.
Although Content Resolver does has a "Diff between views" feature on it's feature roadmap, it's a ways off.

The hardest part of this will be to get buildroot-generator working with the new view.  It's currently a separate program that doesn't use the same configurations as Content Resolver.  It's not an long hard task, but it's much more manual that just adding another yaml file.  If you are wondering, yes, integrating buildroot-generator into Content Resolver is also on our feature roadmap.

**Comment by hroncok** [comment]
I also wonder about source packages that only include a subset of their (sub)packages in ELN. If EPEL needs the rest, what would happen?

**Comment by tdawson** [comment]
This is for ELN Extras, not EPEL.  The ELN repo's have all sub-packages built from the packages.

ELN and EPEL are two totally different communities, with two totally different timelines.
Oddly enough, at the present time, there is a large number of the same people working on both.

I do not agree that the goal of ELN Extras should be to feed EPEL.  That would be three years of wasted Fedora resources.

I was told that people/companies are doing tests on ELN and need extra packages to do those tests.  I am fine with that and feel that is a good goal.
I am also aware that people could use ELN Extras to see what people want for EPEL.  I'm ok with that.
But to say that a goal of ELN Extras is to feed EPEL, and we should account for those EPEL'isms, I'm not ok with.

**Comment by tdawson** [comment]
Wow, that sounded harsh.
I'm trying to prevent scope-creep for both ELN and EPEL.

**Comment by hroncok** [comment]
Sorry for the confusion. Your reply did not sound harsh when I read it in my head. 

About the same problem, sans the EPEL name:

> The ELN repo's have all sub-packages built from the packages.

Oh, unlike RHEL then. Didn't know that. So the missing+needed transitive dependencies for those would be part of ELN Extras?

**Comment by hroncok** [comment]
Also note that the ticket here actually talks about EPEL.

I agree that using ELN Extras for EPEL would just be wasting Fedora resources for 3 years. But I might say that about ELN for the next 3 years as well (we'll see how it actually goes after EL 9 is out).

**Comment by tdawson** [comment]
I might have spoken too soon, and you might have a point, but I think it might still work out.

In the koji buildroot, all the subpackages are available, so if there is a build dependency, you don't have to worry about that.

BUT, the ELN compose is divided up into the various BaseOS, AppStream, and CRB. So runtime (vs buildtime) packages might be missing.

BUT, we would have them available.  So if we make another repo, Extras, we should be able to pull those missing runtime dependencies into the Extras repo.

**Comment by hroncok** [comment]
Yeah, Koji sees them. But Koji also sees rawhide.

**Comment by tdawson** [comment]
Yep.  But I'm hoping that Content Resolver would find all the runtime and buildtime packages we need, and pull them into the Extras "repo" or "list of packages" (I don't know what to call it).
If we do grab a rawhide package or two, it's pretty easy to spot.

Anyway, in short, we need to get Content Resolver going with the new view.  The build-time stuff should take care of itself.  And we'll have to see how things work out with the runtime repo.

I just don't want us adding extra functions in content resolver to try and make things the same as they will be in EPEL.

**Comment by asamalik** [comment]
I'm working on a feature for [Content Resolver](https://tiny.distro.builders/) that will allow us to resolve an extra set of packages on top of the whole ELN set, but keep it on the side.
