### ISSUE TITLE
Create lorax-templates-eln

### ISSUE THREAD

**Issue by hanzz** [fedora-eln/eln#46]
Similar to lorax-templates-rhel or lorax-templates-generic in fedora, we need lorax-templates-eln which would install following files:

https://odcs.fedoraproject.org/composes/lorax-templates/

We can then stop using this hack to get custom templates to Fedora ELN process and we can just normally install the lorax-template-eln file from Koji "eln-build" tag.

**Comment by tdawson** [comment]
lorax-templates-generic is a subpackage of lorax.
lorax-templates-rhel is it's own package.

Does anyone have a preference on having lorax-templates-eln a sub-package to lorax, or be it's own package?

My preference is to have it be a sub-package of lorax.

**Comment by sgallagher** [comment]
We decided with Brian Lane to make this its own package that we can use as the upstream for RHEL N+1 in ELN, so I've submitted a review request here: https://bugzilla.redhat.com/show_bug.cgi?id=1957929

**Comment by sgallagher** [comment]
Built and will be available for the next ELN compose.
