### ISSUE TITLE
Analyze resource usage for ELN builds

### ISSUE THREAD

**Issue by tstellar** [fedora-eln/eln#47]
Determine how much koji builder resources are used by ELN.  This is a prerequisite for #40.

**Comment by tstellar** [comment]
Here is some data I pulled from koji.

Latest Builds of All Packages (resources required to do a mass rebuild):
Arch | Tasks | Duration (Hours) | Host Cores * Hours | Cores per Task 
-------|---------|------------------------|----------------------------|---------------------
noarch | 9106 | 194 | 1579 | 7.76
armhfp  | 4 | 0  | 0 | 1.00
aarch64  | 2082 | 283 | 5322 | 21.33
i386 | 2052 | 132 |  3350 | 23.49
ppc64le | 2081 |  207 | 1625 | 7.77
s390x | 2042 | 324 | 750 | 2.51
x86_64 | 2111 | 135 |  3473 | 24.27

April Builds:
Arch | Tasks | Duration (Hours) | Host Cores * Hours | Cores per Task 
-------|---------|------------------------|-------------------------|---------------------
noarch | 1071 | 19 | 148 | 8.68
aarch64  | 386 | 148 | 1365 | 17.70
i386 | 358 | 42 |  1247 | 34.71
ppc64le |  385 |  94 | 746 | 7.87
s390x | 378 | 125 | 289 | 2.51
x86_64 | 389 | 56 | 1872 | 35.12

**Comment by yselkowitz** [comment]
Is this still relevant?

**Comment by tstellar** [comment]
No, I've stopped pursing this and have been using COPR instead.
