### ISSUE TITLE
Gating Test: Compare ELN build to RHEL build

### ISSUE THREAD

**Issue by rlemosor** [fedora-eln/eln#49]
We want to make sure that packages have the right conditionals in ELN so that they are producing an equivalent package to RHEL. One thing we can do to detect this earlier is write a gating test that compares the RHEL build to the ELN build. (For a place to start, we could confirm that the binary packages produce the same filenames.)

**Comment by sgallagher** [comment]
This probably isn't actually possible, since ELN will always be working on the NEXT major release of RHEL, so changes are expected.
