### ISSUE TITLE
Create removal and add script to eln-periodic pipeline

### ISSUE THREAD

**Issue by rlemosor** [fedora-eln/eln#51]
Packages are removed and added to Content Resolver all the time. We need a way to add and remove the packages automatically.

Removing Steps:
1- Determine if the package is still in Content Resolver list.
2- Untag the package from eln

Adding Steps:
1- See if there is an ELN tagged package for the packages in Content Resolver
2- If there is not an ELN tagged build for the package
2a- (Currently) Attempt a build of the package
2b- If that build fails
2b1- If it fails because there is already a package with that NVR, tag that package already built NVR into ELN.

Problems:
1- The big problem is with "Adding Steps - 2, 2b1". There is currently no way of checking if the package failed because there is already a built NVR.

**Comment by sgallagher** [comment]
https://gitlab.com/redhat/centos-stream/ci-cd/distrosync/distrobuildsync/-/merge_requests/32 should handle this.
