### ISSUE TITLE
Create process for ELN-specific changes that cannot go to Rawhide

### ISSUE THREAD

**Issue by sgallagher** [fedora-eln/eln#56]
### What does the ELN SIG need to do?

In nearly all cases, we want the `rawhide` branch in dist-git to provide the sources used to build packages for ELN. This ensures that they are kept up to date and minimizes packager effort (since they do not have to maintain an extra branch).

However, there are some cases where changes desired for ELN (and by extension, enterprise linux) cannot go into Rawhide. A non-exhaustive list:
* ELN wants to build without documentation, experimental features or similar and the maintainer refuses to include `%{rhel}` conditionals in the spec
* Fedora wants to use the latest version of an upstream, but ELN wants to stay on LTS releases (e.g. Firefox)
* A package is retired in Rawhide but is needed as a dependency for a package in ELN (usually as a result of the previous example)
* A package exists solely for use in ELN (e.g. lorax-templates-rhel)

I'm sure there are other good examples, but these are what I could come up with off the top of my head.

Maintaining a separate branch for ELN requires us to do the following things:
* Create an `eln` branch for the package
* Exclude the package from the Rawhide auto-rebuild

Maintaining an extra branch is more work for the packager, so it should be avoided whenever possible. We should also look into the possibility of extending the auto-rebuilder to attempt a merge-and-scratch-build from Rawhide to the ELN branch, to reduce maintainer effort.

I will start a thread on the Fedora Devel mailing list to elicit other ideas.

**Comment by sgallagher** [comment]
Thread started:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/44JTGXWOLMIYH26VHXEFKDQEDWUY3H3Z/

**Comment by sgallagher** [comment]
I think the plan was largely accepted on Fedora Devel, so the remaining task here is to document it.

**Comment by yselkowitz** [comment]
https://docs.fedoraproject.org/en-US/eln/eln-branch/
