### ISSUE TITLE
TASK: Fix ELN compose

### ISSUE THREAD

**Issue by voxik** [fedora-eln/eln#58]
### What does the ELN SIG need to do?

It seems that content resolver does not provide [up2date results](https://github.com/minimization/content-resolver-input/issues/589), because ELN compose is broken for 16 days already. It would be nice to have it fixed

**Comment by sgallagher** [comment]
I didn't realize it was broken. I have automation that is supposed to let me know when a compose is DOOMED, but I just discovered that the `latest` symlink appears not to be getting updated properly, so my detection script was always pointing at an old successful compose.

I'll see what I can do about the current breakage, but I'd like @hanzz to take a look at what's up with the `latest` symlink (at the top-level, not the `production` symlink which seems to be fine).

**Comment by sgallagher** [comment]
The current compose issue is actually a bug on the Koji side: https://pagure.io/koji/issue/2897

I'll lean on them to get that fixed ASAP. Thanks for the report.

**Comment by jkonecny12** [comment]
Hi, are the composes back again? If yes, I guess we can close this issue?

**Comment by sgallagher** [comment]
Yes, they are. I forgot to close this ticket. Thanks!
