### ISSUE TITLE
TASK: Compose doesn't contain cppcheck & python3-lxml

### ISSUE THREAD

**Issue by jkonecny12** [fedora-eln/eln#59]
### What does the ELN SIG need to do?
Hi, to run tests of Anaconda we need `cppcheck` and `python3-lxml` packages. However, these are missing in ELN x86-64 container. May I ask where could I find those?

**Comment by sgallagher** [comment]
@jkonecny12 If you need packages that are not part of ELN, you have three choices:

1. Add them to ELN by including them as a `BuildRequires` of `anaconda`.
2. Add them to ELN by including them in the [Anaconda workload configuration](https://github.com/minimization/content-resolver-input/blob/master/configs/sst_front_door-anaconda.yaml).
3. Install `fedora-repos-rawhide` and install it from there.

**Comment by hroncok** [comment]
That is weird. python3-lxml is in our workload directly.

**Comment by hroncok** [comment]
See https://tiny.distro.builders/view-rpm--view-eln--python3-lxml.html

**Comment by sgallagher** [comment]
Hmm, looks like more fallout from my accidental untagging of things. You're right, `python-lxml` should be in ELN but is not. However, it appears that `cppcheck` was dropped at some point (probably something else had it as a BuildRequires and no longer does).

**Comment by jkonecny12** [comment]
Ahh, interesting. The problem here is that this is not Anaconda build requires but only test run requires and Anaconda does not have tests run during build.

**Comment by sgallagher** [comment]
Ah right, I had untagged `python-lxml` because it had accidentally gotten built against Python 3.9. I'm not sure why I missed rebuilding it for 3.10, but I'm doing that now.

**Comment by jkonecny12** [comment]
Any idea how to get the `cppcheck` back without adding "false" dependency to Anaconda?

**Comment by hroncok** [comment]
Add it to our workload in https://github.com/minimization/content-resolver-input

**Comment by sgallagher** [comment]
@jkonecny12 If you don't need it in the buildroot or at runtime, probably the best option would be to install `fedora-repos-rawhide` and install it from there. We don't really want to include anything in ELN that is not strictly necessary.

I'm still working on getting `python-lxml` built; there was an issue with shadow-utils breaking the ELN buildroot that I just fixed.

**Comment by jkonecny12** [comment]
@sgallagher ok, so now I wonder what is the better way to go. One the one hand it will be easier to just use `fedora-repos-rawhide` (even thought, it could raise new conflicts etc...), on the other hand we want to have `cppcheck` even on next RHEL so the content resolver seems like a correct thing to do...

**Comment by sgallagher** [comment]
If it is actually desired for inclusion into RHEL 10, then it belongs in one of the workload definitions. You'll need to confirm that with the Red Hat Engineering team that maintains it and have them add it to their workload.

**Comment by sgallagher** [comment]
OK, `python-lxml` just finished building and should be present as soon as the buildroot refreshes. As for cppcheck, you'll need to decide how you want to handle that.

**Comment by jkonecny12** [comment]
Ok, thanks a lot for your help. Feel free to close this issue.
