### ISSUE TITLE
Please do not close Fedora bugs

### ISSUE THREAD

**Issue by pvalena** [fedora-eln/eln#6]
The bugs are closed (by Bodhi), because it has "close bugs on stable" set for ELN updates. This also happens even if I build the package in side-tag (or a number of them), and that may take some time until it gets a bodhi update as well.

Example: https://bugzilla.redhat.com/show_bug.cgi?id=1877502

_ _ _ _

Note: the bugs were not added automatically due to [this bodhi issue](https://github.com/fedora-infra/bodhi/issues/4138).

**Comment by hroncok** [comment]
See also https://pagure.io/fedora-infrastructure/issue/9191

**Comment by sgallagher** [comment]
This was tracked in
https://github.com/fedora-infra/bodhi/issues/4094
