### ISSUE TITLE
TASK: python3-rpm-generators package can't be found

### ISSUE THREAD

**Issue by jkonecny12** [fedora-eln/eln#62]
### What does the ELN SIG need to do?
Hi, I have problem to install `rpm-build` package together with `python3-devel` in the ELN-x86_64 container because required package `python3-rpm-generators` can't be found.

Steps to reproduce:
* ``podman pull quay.io/fedoraci/fedora:eln-x86_64``
* ``podman run -it --rm fedora:eln-x86_64``
* ``dnf install python3-rpm-generators`` or ``dnf install rpm-build python3-devel``

The output is:
```
Error:
 Problem: package python3-devel-3.10.0~b2-3.eln112.x86_64 requires (python3-rpm-generators if rpm-build), but none of the providers can be installed
  - cannot install the best candidate for the job
  - conflicting requests
```

Could you please take a look why is this happening?

**Comment by hroncok** [comment]
The latest ELN build of python-rpm-generators is quite old and not tagged anywhere: https://koji.fedoraproject.org/koji/packageinfo?packageID=24201

**Comment by sgallagher** [comment]
Hmm, I'm not sure why it isn't being rebuilt; it definitely appears in the Content Resolver: https://tiny.distro.builders/view-srpm--view-eln--python-rpm-generators.html

I'll look into that, but in the meantime I'll manually trigger a rebuild.

**Comment by sgallagher** [comment]
It rebuilt successfully for ELN and will be in the next compose. @bookwar can you check the rebuilder logs? I can't figure out why it wasn't being picked up, since it's been in the CR list for six months.

**Comment by sgallagher** [comment]
This should be fixed now. I just verified that the latest compose now contains this package.

**Comment by jkonecny12** [comment]
Thanks!

**Comment by jkonecny12** [comment]
Note: waiting for a new compose to verify this and than I'll close this issue.

**Comment by jkonecny12** [comment]
Solved, thanks everyone.
