### ISSUE TITLE
TASK: Fix broken composes because of `rust-zram-generator` has other name in Fedora

### ISSUE THREAD

**Issue by jkonecny12** [fedora-eln/eln#63]
### What does the ELN SIG need to do?
Please fix broken composes because of `rust-zram-generator`.

The text below doesn't apply, see https://github.com/fedora-eln/eln/issues/63#issuecomment-891941195. Thanks for explanation @sgallagher .
~Hi everyone, I would like to kindly ask you to increase how often the composes are created. Ideally once a day.~

~#### Reasoning:~
~We (Anaconda) used ELN testing on PRs testing which worked nice for a while but right now there are never ending issues and we had to disable these on PRs otherwise they would be RED all the time. I always file an issue here and it is resolved quickly but then we are waiting more than a week for a compose (usually). This situation is a bit unbearable and we even thought in the team if we really want to test against the ELN...
I'm trying to defend the ELN testing (just the background task now not PR testing) because it helped us to discover some issues in the past before they appeared in RHEL. However, right now, we are again waiting 8 days for a compose with the last fix which even blocks COPR builds (Packit). Currently our last successful run was 3 moths ago.
In the current scenario, before the compose is created to resolve some old issue, the new issue is crawling behind the scene. By having composes daily we could quickly get rid of these.~

~Please make ELN more stable platform by increasing cadence of composes.~

**Comment by sgallagher** [comment]
@jkonecny12 They run every day at 00:00 UTC, but most recently they have been broken because anaconda added a dependency on `rust-zram-generator` which is named differently in Fedora ELN and RHEL. The composes are now failing because the dependencies cannot be resolved.

**Comment by sgallagher** [comment]
@msekletar I think the correct solution here is for you to change the binary RPM names for RHEL to match those in Fedora (so that RHEL and Fedora both expect `zram-generator` rather than `rust-zram-generator`) and then anaconda can correct its dependency.

**Comment by jkonecny12** [comment]
@sgallagher ahh, ok, so it's broken by us now... Sorry for this issue. In that case I wonder how to improve the broken issues. I'll start to follow koji compose build to know what is happening.

**Comment by msekletar** [comment]
Name change was not intentional. I will change it back to match ELN and Fedora.

**Comment by sgallagher** [comment]
@msekletar Thanks!

**Comment by jkonecny12** [comment]
> Name change was not intentional. I will change it back to match ELN and Fedora.

If you will also change name of the package on RHEL, please tell us to coordinate spec file change in Anaconda to not break composes. Thanks!

**Comment by jkonecny12** [comment]
Solved now.
