### ISSUE TITLE
TASK: rpm-build and python3-devel can't be installed together

### ISSUE THREAD

**Issue by jkonecny12** [fedora-eln/eln#66]
### What does the ELN SIG need to do?
Anaconda can't be build in ELN mock because the `rpm-build` is removed as dependent package during the preparation phase. See [here](https://download.copr.fedorainfracloud.org/results/@rhinstaller/Anaconda/fedora-eln-x86_64/02523370-anaconda/builder-live.log.gz).

When I reproduce this locally and try to install the `rpm-build` package back I've got this:

```
INFO: installing package(s): rpm-build
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Fedora - ELN - Developmental packages for the next Enterprise Linux rele 6.5 kB/s | 2.3 kB     00:00
Fedora - ELN AppStream - Developmental packages for the next Enterprise  5.2 kB/s | 2.8 kB     00:00
Dependencies resolved.
=========================================================================================================
 Package                      Architecture     Version                              Repository      Size
=========================================================================================================
Installing:
 rpm-build                    x86_64           4.17.0-0.beta1.0.eln112.2            eln             61 k
Installing dependencies:
 systemd-rpm-macros           noarch           249.2-1.eln112                       eln             29 k
Removing dependent packages:
 python3-devel                x86_64           3.10.0~rc1-1.eln112                  @eln           779 k
```

It seems that `python3-devel` can't be installed together with `rpm-build` on ELN. Could you please take a look on why is this happening @sgallagher @hroncok?

**Comment by hroncok** [comment]
python3-devel has:

```
Requires: (python-rpm-macros if rpm-build)
Requires: (python3-rpm-macros if rpm-build)
Requires: (pyproject-rpm-macros if rpm-build)
Requires: (python3-rpm-generators if rpm-build)
```

Are all the required packages installable in ELN?

**Comment by sgallagher** [comment]
`  - nothing provides python3-packaging needed by python3-rpm-generators-12-8.eln112.noarch`

**Comment by hroncok** [comment]
Yeah, it seems that the latest ELN python-packaging build is outdated and untagged.

**Comment by sgallagher** [comment]
Yeah, I'm rebuilding it now

**Comment by hroncok** [comment]
> Yeah, it seems that the latest ELN python-packaging build is outdated and untagged.

And built with Python 3.9.

**Comment by hroncok** [comment]
> Yeah, I'm rebuilding it now

The build failed because of https://github.com/fedora-eln/eln/issues/65

**Comment by sgallagher** [comment]
OK, this is FTBFS until we get Sphinx built.

**Comment by sgallagher** [comment]
This should be fixed now.

**Comment by jkonecny12** [comment]
Great work everyone. Thanks for solving this so quickly!
