### ISSUE TITLE
Buildroot can't be instantiated preventing ELN builds

### ISSUE THREAD

**Issue by jmflinuxtx** [fedora-eln/eln#67]
This started last week:

DEBUG util.py:444:   Problem: package lorax-36.0-1.eln113.x86_64 requires python3-kickstart >= 3.19, but none of the providers can be installed
DEBUG util.py:444:    - package lorax-templates-rhel-10.0-3.eln112.noarch requires lorax >= 34.9.1, but none of the providers can be installed
DEBUG util.py:444:    - package python3-kickstart-3.35-1.eln113.noarch requires python3.10dist(requests), but none of the providers can be installed
DEBUG util.py:444:    - package python3-kickstart-3.35-1.eln113.noarch requires python3-requests, but none of the providers can be installed
DEBUG util.py:444:    - conflicting requests
DEBUG util.py:444:    - nothing provides (python3.10dist(idna) < 3 with python3.10dist(idna) >= 2.5) needed by python3-requests-2.25.1-3.eln112.noarch

**Comment by sgallagher** [comment]
It looks like some python packages were missed in ELN rebuilds around July and until recently we didn't notice because they weren't causing builds to fail. I'm rebuilding these packages now.

**Comment by sgallagher** [comment]
I rebuilt `python-jinja2`, `python-markupsafe`, and `python-requests`, which seems to have resolved this issue. Sorry for the inconvenience.
