### ISSUE TITLE
TASK: Develop process for removing packages from ELN when they are removed from content list

### ISSUE THREAD

**Issue by tdawson** [fedora-eln/eln#70]
### What does the ELN SIG need to do?
* right now we have ways to build and grow the ELN packages.  And there are certain people with permissions to be able to untag packages when they are removed.  But we don't have anything that automatically see's which packages are extra and deletes them after a period of time.
*

**Comment by sgallagher** [comment]
I think this should be handled by https://gitlab.com/redhat/centos-stream/ci-cd/distrosync/distrobuildsync/-/merge_requests/33 once it lands. @tdawson would you mind reviewing that MR?

**Comment by tdawson** [comment]
Sure, but it's a massive MR, gonna take me a while to make it all the way through.

**Comment by sgallagher** [comment]
This is taking place as part of the "cleanup" task in DistroBuildSync now.
