### ISSUE TITLE
TASK: Exclude fedora-release from being auto tagged into ELN

### ISSUE THREAD

**Issue by jmflinuxtx** [fedora-eln/eln#71]
Yesterday, fedora-release was rebuilt for rawhide. As a result, it was auto-tagged into ELN and made ELN identify as Fedora, changing the builds for anyone who special cased.  We need to make sure it doesn't get auto tagged.  Luckily, one of the RHEL kernel developers was doing some work on the spec file and could not figure out why it wasn't doing what he expected, or it might have been quite some time before this was discovered.

**Comment by sgallagher** [comment]
https://gitlab.com/redhat/centos-stream/ci-cd/distrosync/distrobuildsync-config/-/commit/680ceb07ba057301c6f7bbfdb852bf689689b55d
