### ISSUE TITLE
TASK: cmake broken: nothing provides librhash.so.0 needed by cmake-3.22.0-0.3.rc2.fc36.i686

### ISSUE THREAD

**Issue by minfrin** [fedora-eln/eln#72]
### What does the ELN SIG need to do?
*

Builds that depend on cmake currently don't build in ELN, as cmake fails to install, citing missing librhash.so:

```
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides librhash.so.0 needed by cmake-3.22.0-0.3.rc2.fc36.i686
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Copr build error: Build failed
```

Looks like the package `rhash` is required but missing.

**Comment by sgallagher** [comment]
Yeah, this is one of several issues introduced by a mistake I made on Friday that coincided with a libnsl2 soname bump (bad timing).

I'm working on fixing it.

**Comment by sgallagher** [comment]
I think this should be fixed now. We have a functional compose again as of 2021-11-29.

Please reopen it if it persists.
