### ISSUE TITLE
Requesting permission to use the %{eln} macro in python-rpm-macros

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#73]
Full disclosure: We have already done this, but now I [know we should have opened this issue first](https://github.com/fedora-eln/eln-docs/pull/23). Hence opening it in retrospect and am happy to redo things if you reject this request.

In python-srpm-macros, we'd like to keep using the `%{eln}` macro in the [definition](https://src.fedoraproject.org/rpms/python-rpm-macros/pull-request/112) of `%{python_wheel_pkg_prefix}` (and transitively also `%{python_wheel_dir}`).

The values of the macros are (for the prefix and for the dir):

<dl>
  <dt>Fedora Rawhide + older releases</dt>
  <dd><code>python</code> and <code>/usr/share/python-wheels</code></dd>
  <dt>Fedora ELN</dt>
  <dd><code>python</code> and <code>/usr/share/python-wheels</code></dd>
  <dt>RHEL</dt>
  <dd><code>python3</code> and <code>/usr/share/python3-wheels</code> for Python 3 version providing <code>python3</code> and <code>/usr/bin/python3</code> (e.g. 3.9 on RHEL 9)<br>
          <code>python3.X</code> and <code>/usr/share/python3.X-wheels</code> for all the other Python 3.X versions</dd>
</dl>

Note that the ELN and Rawhide+ values are identical, but the RHEL value is different. Hence, we cannot just use the `%{fedora}` or `%{rhel}` macros, we need to use the otherwise forbidden `%{eln}` macro.

The definition is pasted here for completeness:

```
%python_wheel_pkg_prefix python%{?rhel:%{!?eln:%{python3_pkgversion}}}
%python_wheel_dir %{_datadir}/%{python_wheel_pkg_prefix}-wheels
```

## Why does the value of `%{python_wheel_dir}` need to differ on RHEL and Fedora?

The main reason for this difference is the difference in the life cycle of the two distributions.

 - In Fedora, we build Python wheels from the python-pip, python-setuptools, and python-wheel components just once and we instruct all our Python interpreters to look them up in a common directory. When we ship a Python version that no longer works with our wheels, we keep Python-upstream-provided wheels bundled in Python instead with all the risk and challenges that it brings. Fedora has only one parallel-installable Python stack, other interpreters are provided without extra packages (with the exception of a handful of Python 2 packages that we would like to eventually drop).
 - In RHEL we (plan to) build the newer version of setuptools/pip/wheel for newer Python versions and hence we (plan to) build newer versions of the wheels and install them to distinct locations namespaced by the Python version. RHEL will most likely have several parallel-installable Python stacks (gradually added to the distro).

## Why cannot the value of `%{python_wheel_dir}` differ between ELN and Fedora Rawhide?

Python depends on the wheels and expects them to be in `/usr/share/python-wheels`. As Rawhide builds are regularly used to bootstrap the ELN builds, we need the ELN builds of Python to be compatible with Rawhide wheels and vice versa.

## Why does the value of the two macros need to differ between RHEL and ELN?

That is the only logical conclusion of the previous two constraints:

    (RHEL != Rawhide) && (Rawhide == ELN) => (RHEL != Rawhide == ELN)  => (RHEL != ELN)

Or:

```
    Rawhide
    /     \
   =       ≠
  /         \
ELN——— ≠ ———RHEL
```

## What happens if we cannot do this?

If we cannot do this we would need to [keep changing](https://bugzilla.redhat.com/show_bug.cgi?id=1982668) the value of `%{python_wheel_pkg_prefix}` each time CentOS Stream (RHEL) forks from Fedora ELN. We'd rather not have to do that as it poses a significant risk of being introduced late in the release cycle.

---

Note that even if we could maintain a separate branch for ELN's python-rpm-macros (which is what I usually prefer over conditionals), we would not be able to achieve this difference, as we would need to distinguish between ELN and RHEL.

**Comment by sgallagher** [comment]
My ideal outcome would be for us to have the ELN python packages be identical to the RHEL ones, but there are a number of ways that this can go wrong in addition to the ones you've listed here, so for the time being I think this is the only reasonable approach to the problem. Thanks for bringing it to our attention (and for the extremely detailed explanation!).

**Comment by sgallagher** [comment]
This was approved at the 2021-11-19 meeting, but I forgot to close this ticket.

> The python macros are permitted to use the %eln macro as described in https://github.com/fedora-eln/eln/issues/73
