### ISSUE TITLE
TASK: Enable scratch-build Zuul CI check for ELN on Rawhide merge requests

### ISSUE THREAD

**Issue by sgallagher** [fedora-eln/eln#75]
### What does the ELN SIG need to do?
~~* Define the rpminspect configuration for ELN (derived from the RHEL configuration)~~
~~* Enable rpminspect checks as part of gating for the automatic Bodhi updates.~~

~~Requested delivery: Q1 2022~~

Add a Zuul CI pipeline to perform a non-voting scratch-build test for ELN on all Rawhide merge requests for packages in the ELN content set.

**Comment by sgallagher** [comment]
Note: this has important consequences for the RHEL Automotive team, so they'd appreciate a timely delivery.

**Comment by sgallagher** [comment]
@dcantrell Would you be able to help with this?

**Comment by dcantrell** [comment]
Yes, what do you want me to do?

**Comment by sgallagher** [comment]
@dcantrell Can you help us get Bodhi configured to automatically run rpminsepect when an update for ELN is created (and how to get it set up to use an ELN/RHEL rpminspect config rather than the Fedora one)?

**Comment by dcantrell** [comment]
For the integration, I think @morucci can help because that would be through Zuul.

For the configuration, I can help with that directly.  I think it would make sense to add the ELN-specifics to the rpminspect-data-fedora package.  Perhaps as a profile, which overlays the main fedora.yaml configuration.  Invocation of rpminspect ELN jobs would then be "rpminspect-fedora -p eln" or whatever we name the profile.  Or would you prefer having a separate rpminspect-data package specific to ELN?

**Comment by morucci** [comment]
Hi, Zuul can trigger jobs based on Pull Request (or other code review providers) events. So that won't work based on Koji builds except with a bridge (which is a workaround that need to be maintained).

**Comment by tflink** [comment]
Is this something that needs to be done?

**Comment by sgallagher** [comment]
I spoke with @bookwar about this a couple weeks ago. We're revising this to "Pull requests into Rawhide should run an ELN mock-build (non-voting) and report success or failure". I'll update the summary.

**Comment by hroncok** [comment]
Would it make sense to run a Koji scratchbuild instead?

**Comment by sgallagher** [comment]
> Would it make sense to run a Koji scratchbuild instead?

Long-term, maybe? For an immediate win, I'd like us to just take the existing mock-build test and run it with the ELN configuration.

**Comment by hroncok** [comment]
I might be confused by what you mean when you say *existing* here because I see an rpm-scratch-build Zuul job in Fedora PRs (but it does not build for ELN) but I see no mock-build test in Fedora PRs.

**Comment by sgallagher** [comment]
> I might be confused by what you mean when you say _existing_ here because I see an rpm-scratch-build Zuul job in Fedora PRs (obviously, it does not build for ELN at this moment) but I see no mock-build test in Fedora PRs.

You are correct. I was going from flawed memory. The point was "do what Fedora is doing, not something new".

**Comment by bookwar** [comment]
I have created a "prototype" for the change in this MR https://pagure.io/fedora-zuul-jobs-config/pull-request/178

It adds one job called check-for-eln which for now just returns true (echo project name) and then if successful it adds a eln-scratch-rpm-build job which runs the scratch build.

So we need two more things
1) way to check if zuul.project.short_name is a part of ELN
Some curl request to Content resolver?
 
2) way to convert this change in yaml into the change in the original dhall config here: 
https://pagure.io/fedora-project-config/blob/master/f/FZCI.dhall/fedora-zuul-jobs-config/jobs.dhall

**Comment by sgallagher** [comment]
> > I have created a "prototype" for the change in this MR https://pagure.io/fedora-zuul-jobs-config/pull-request/178
> > It adds one job called check-for-eln which for now just returns true (echo project name) and then if successful it adds a eln-scratch-rpm-build job which runs the scratch build.
> > So we need two more things
> > 
> > 1. way to check if zuul.project.short_name is a part of ELN
> >    Some curl request to Content resolver?
> 
> `curl https://tiny.distro.builders/view-all-source-package-name-list--view-eln.txt` will give you the complete list of eligible SRPM package names. You can check presence in that list.

Actually, we may want to also include https://tiny.distro.builders/view-all-source-package-name-list--view-eln-extras.txt to that, so we also test contents of ELN-Extras, not just ELN.

**Comment by bookwar** [comment]
For the first part (recognize ELN) I've set it up in this form:
 https://pagure.io/fedora-zuul-jobs-config/pull-request/179 

For the second I got some pointers from Fabien, work in progress in https://pagure.io/fedora-project-config/pull-request/277

**Comment by hroncok** [comment]
I keep getting Zuul failures now:

```
The conditional check 'scratch_build' failed. The error was: error while evaluating conditional (scratch_build): 'scratch_build' is undefined

The error appears to be in '/var/lib/zuul/builds/9f2c70a501344b0587199623c2a563ae/trusted/project_3/pagure.io/fedora-zuul-jobs-config/playbooks/koji/build-ng.yaml': line 14, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      become: true
    - include_role:
      ^ here
```

**Comment by morucci** [comment]
Here is the change to fix the job: https://pagure.io/fedora-project-config/pull-request/281 and the auto generated change is https://pagure.io/fedora-zuul-jobs-config/pull-request/182

**Comment by bookwar** [comment]
Thanks for fixing it @morucci 

We now have a first green run https://fedora.softwarefactory-project.io/zuul/build/2c08e751337e4224820bfc5ba24d9edf

Note that it is only an x86 build, and we trigger only on rawhide branch for now. There is no Zuul trigger for the `eln` branch.

@sgallagher Would you write a mail to devel-list introducing this test?
