### ISSUE TITLE
TASK: Getting 403 when downloading packages from ELN mirror

### ISSUE THREAD

**Issue by jkonecny12** [fedora-eln/eln#76]
We are facing issue when building our test containers for ELN that we are getting 403 (forbidden) when downloading some packages. These package set changed during the time:

Three days ago it was cmake package: https://github.com/rhinstaller/anaconda/runs/4318575973?check_suite_focus=true#step:3:1248
Two days ago it was python3-setuptools: https://github.com/rhinstaller/anaconda/runs/4338526352?check_suite_focus=true#step:3:354
And now it is kernel-srpm-macros: https://github.com/rhinstaller/anaconda/runs/4350828733?check_suite_focus=true#step:3:249

The broken packages seems to not change during the same day (couple of days). First I thought it's because of https://github.com/fedora-eln/eln/issues/72 but now it's not just `cmake` package.

To download packages we are using https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/ in our [repo file](https://github.com/rhinstaller/anaconda/blob/master/dockerfile/anaconda-ci/eln.repo#L3).

**Comment by sgallagher** [comment]
The ELN compose has been broken since Nov. 11th. I've been struggling to get it back into working order and I hope to have it working again within the next day or so. Sorry for the inconvenience.

That said, I'm not sure why the packages in `latest-Fedora-ELN` wouldn't be working; that was the last good compose.

**Comment by sgallagher** [comment]
@jkonecny12 I believe this should be resolved now, can you confirm?

**Comment by jkonecny12** [comment]
Seems to be working now. 
https://github.com/rhinstaller/anaconda/actions/runs/1528432304

Thanks!
