### ISSUE TITLE
TASK: Switch ppc64le to POWER9 baseline

### ISSUE THREAD

**Issue by fweimer-rh** [fedora-eln/eln#78]
Downstream is using `-mcpu=power9`. We felt we couldn't do this in Fedora at the time, so we never upstreamed.

I do not see anything obvious that would block this change infrastructure-wise. Shall we give it a try? glibc has a pretty effective run-time check, so would notice incompatibilities soon once it is rebuilt.

**Comment by sgallagher** [comment]
I think it's probably the right time to do so, yes.

**Comment by fweimer-rh** [comment]
I plan to implement this next week, after the Fedora rawhide mass rebuild is mostly done. The change is technically independent, but there's no need to interfere with the ongoing mass rebuild in case I make a mistake in the change.
