### ISSUE TITLE
multi-arch manifest at https://quay.io/repository/fedoraci/fedora&tab=tags does not include s390x

### ISSUE THREAD

**Issue by mh21** [fedora-eln/eln#81]
While individual images are available for amd64/aarch64/s390x/ppc64le, the multi-arch manifest only covers amd64/aarch64/ppc64le.

_Originally posted by @mh21 in https://github.com/fedora-eln/eln/issues/16#issuecomment-989306363_

**Comment by sgallagher** [comment]
@hanzz Can you please have a look at this?

**Comment by mh21** [comment]
Friendly ping, the multi-arch manifest is stale 😕

**Comment by mh21** [comment]
friendly ping 🤗

**Comment by sgallagher** [comment]
@hanzz Can you please check into this? You set this up in the first place and I have no idea where the configuration/service that is pushing these to Quay.io exists.

**Comment by mh21** [comment]
@sgallagher friendly ping, is there anything I can do to get this finally fixed after more than two years 😂?

**Comment by sgallagher** [comment]
@mh21 I spent much of Friday trying to track this down and I haven't been able to find it. I'll keep digging.

**Comment by sgallagher** [comment]
@mh21 I finally tracked down the code repo for this. It's https://github.com/fedora-ci/eln-upload-container-images

Interestingly, I also see that you're actually a committer there.

**Comment by sgallagher** [comment]
@mh21 Actually... it looks like you yourself are the author of the commit that disabled s390x from the manifest: https://github.com/fedora-ci/eln-upload-container-images/commit/c3ee1631ae92bcd4242fc4aa6785e3614e4a4c17

**Comment by mh21** [comment]
yes, as said in the [corresponding merge request](https://github.com/fedora-ci/eln-upload-container-images/pull/2#issuecomment-760987285)

> disable s390x until there is an image for that arch
