### ISSUE TITLE
TASK: enable BaseOS installer for s390x

### ISSUE THREAD

**Issue by sharkcz** [fedora-eln/eln#84]
### What does the ELN SIG need to do?
* Currently the BaseOS compose for s390x doesn't contain installer files, please enable them in the compose config. It's a difference to other arches and breaks mirroring ELN into internal beaker.

**Comment by sgallagher** [comment]
https://pagure.io/pungi-fedora/pull-request/1064

**Comment by sgallagher** [comment]
This should be fixed as of the most recent compose.
