### ISSUE TITLE
Document differences between Rawhide and ELN

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#9]
Could https://docs.fedoraproject.org/en-US/eln/ please include an up to day list of differences between Rawhide and ELN? E.g.:

- the dist tag is different
- armv7hl is missing
- gcc was updated to 11
- ...

Thanks.

**Comment by sgallagher** [comment]
@bookwar Are you still planning to work on this, or should we find someone else to work on general documentation tasks?

**Comment by tdawson** [comment]
Here is a pull request with the answer on the FAQ page
https://github.com/fedora-eln/eln-docs/pull/23

Here is what the page will look like.
https://tdawson.fedorapeople.org/eln/public/eln/faq/

**Comment by tdawson** [comment]
Documentation has been updated.
- FAQ has been updated with the question about what the difference is between Rawhide and ELN
- - https://docs.fedoraproject.org/en-US/eln/faq/
- Part of that FAQ Question points to the buildroot documentation, which has also been updated with the most current info.
- - https://docs.fedoraproject.org/en-US/eln/buildroot/

**Comment by tdawson** [comment]
I believe we have finished this issue, but I'll leave it open for a day or two, to make sure.

**Comment by hroncok** [comment]
Thank you for this!
