### ISSUE TITLE
Should Fedora ELN require POWER 9 ?

### ISSUE THREAD

**Issue by davide125** [fedora-eln/eln#90]
Raised in https://bugzilla.redhat.com/show_bug.cgi?id=2077299 -- el9 currently requires POWER 9, while Fedora requires POWER 8. Should ELN require POWER 9 as well?

**Comment by hroncok** [comment]
Yes, see https://github.com/fedora-eln/eln/issues/78

**Comment by davide125** [comment]
Perfect, thanks!
