### ISSUE TITLE
QUESTION: How to properly build Rust in ELN?

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#91]
I've just noticed that python-cryptography FTBFS in ELN because:

```
DEBUG util.py:444:  No matching package to install: 'rust-toolset'
DEBUG util.py:444:  Not all dependencies satisfied
DEBUG util.py:444:  Error: Some packages could not be found.
```

The spec file has:

```
%if 0%{?fedora}
BuildRequires:  rust-packaging
%else
BuildRequires:  rust-toolset
%endif
```

Is this supposed to work, or should the specfile use the otherwise forbidden `0%{?eln}` conditional?

cc @tiran

**Comment by hroncok** [comment]
(This will be an actuall issue for the Python 3.11 rebuild in ~1 month.)

**Comment by cuviper** [comment]
As of [rust-1.61.0-2.eln118](https://koji.fedoraproject.org/koji/buildinfo?buildID=1970186), there is now a rust-toolset subpackage for `%{rhel}` -- let me know if that works!

**Comment by sgallagher** [comment]
Sorry, it took a while to get back to this, but I have good news! python-cryptography built successfully in ELN for the first time this week.

Thanks, @cuviper

**Comment by sgallagher** [comment]
On Tue, May 31, 2022 at 8:38 PM Josh Stone ***@***.***> wrote:

> As of rust-1.61.0-2.eln118
> <https://koji.fedoraproject.org/koji/buildinfo?buildID=1970186>, there is
> now a rust-toolset subpackage for %{rhel} -- let me know if that works!
>

Sorry, it took a while to get back to this, but I have good news!
python-cryptography built successfully in ELN for the first time this week.

Thanks, Josh!
