### ISSUE TITLE
Booting from install tree doesn't load stage2

### ISSUE THREAD

**Issue by sgallagher** [fedora-eln/eln#93]
It appears that attempts to boot directly from https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/ gets the wrong kernel command-line and thus is unable to load stage2 and anaconda.

**Comment by t184256** [comment]
Not sure what you're referring to.
Closest one I've observed would be better described like this: installation used to boot, install and leave the installed system with the incorrect commandline in the bootloader, unbootable. That one was [workaroundable by manually intervening post-installation](https://github.com/t184256/fingertip/blob/5c3f718f02ec603987a658990ecc84f0addf1cbc/fingertip/plugins/os/fedora_eln.py#L84).

**Comment by sgallagher** [comment]
It looks like this is an issue in either virt-install or osinfo-db. I've opened a [ticket](https://github.com/virt-manager/virt-manager/issues/397) against virt-install to look into it further.

**Comment by t184256** [comment]
Guess you've found yet another bug, since I haven't tried virt-install.

**Comment by sgallagher** [comment]
OK, I've got this one fixed by https://pagure.io/pungi-fedora/pull-request/1102

This will now resolve as `fedora-unknown` and properly reach the installer. I'm also working on a patch to `osinfo-db` to recognize Fedora ELN properly.
