### ISSUE TITLE
TASK: ELN CI

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#96]
### What does the ELN SIG need to do?
Please, when a Fedora dist-git PR is opened for rawhide for a package that exists in ELN:

 * at the very least, scratch build that package in ELN
 * ideally, also run STI and TMT tests on ELN

If this does not happen, failures are only to be discovered after the merge, like in https://github.com/fedora-eln/eln/issues/80#issuecomment-1147358035

Thanks

**Comment by sgallagher** [comment]
Duplicate of #30

**Comment by hroncok** [comment]
Indeed, sorry about the noise.
