### ISSUE TITLE
TASK: Please provide libtimezonemap-devel

### ISSUE THREAD

**Issue by VladimirSlavik** [fedora-eln/eln#98]
### What does the ELN SIG need to do?
* Please provide the `libtimezonemap-devel` package

### Why?
* Anaconda does not build without that, see https://github.com/rhinstaller/anaconda/pull/4196

**Comment by sgallagher** [comment]
https://pagure.io/fedora-comps/pull-request/745

**Comment by VladimirSlavik** [comment]
PR has been merged, thank you!
